/*
===============================================================================
Creator : Ceri Binding, University of South Wales ceri.binding@southwales.ac.uk
Project : Any
Classes : uri.RDF, uri.RDFS, uri.SKOS, uri.SKOSXL, uri.CRM, uri.CRMEH, uri.DC, 
          uri.DCTERMS, uri.DCMI, uri.DCAM, uri.FOAF, uri.OWL, uri.SCHEMA
Summary : Constants for case-sensitive entity and property URIs for RDF apps 
Example : alert(uri.RDF.BAG) | alert(uri.RDF["BAG"])
          either results in "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag"
License : http://creativecommons.org/publicdomain/zero/1.0/ 
===============================================================================
History :
11/03/2015 CFB Adapted from old STAR script. Added SKOS mapping properties
13/04/2015 CFB Added FOAF, DCAM & DCMI URIs, missing DCTERMS properties, NS,
   DC Encoding Schemes and DCMI Type vocabulary, constants sorted alphabetically
10/02/2023 CFB Change to ES6 template strings (as it is 2023). drop 'usw' prefix
===============================================================================
*/

// define base namespace
var uri = this.uri || {}  

/*
uri.RDF
usage: alert(uri.RDF.BAG) | alert(uri.RDF["BAG"])
both return "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag"
*/
uri.RDF = { NS: "http://www.w3.org/1999/02/22-rdf-syntax-ns#" }
uri.RDF = {
    NS: uri.RDF.NS, // else it is overwritten
    // entities
    ALT: `${uri.RDF.NS}Alt`,
    BAG: `${uri.RDF.NS}Bag`,
    LIST: `${uri.RDF.NS}List`,
    PROPERTY: `${uri.RDF.NS}Property`,
    SEQ: `${uri.RDF.NS}Seq`,
    STATEMENT: `${uri.RDF.NS}Statement`,
    XMLLITERAL: `${uri.RDF.NS}XMLLiteral`,
    // properties
    FIRST: `${uri.RDF.NS}first`,
    ID: `${uri.RDF.NS}ID`,
    OBJECT: `${uri.RDF.NS}object`,
    PREDICATE: `${uri.RDF.NS}predicate`,
    REST: `${uri.RDF.NS}rest`,
    SUBJECT: `${uri.RDF.NS}subject`,
    TYPE: `${uri.RDF.NS}type`,
    VALUE: `${uri.RDF.NS}value`
}

/*
uri.RDFS
usage: alert(uri.RDFS.LITERAL) | alert(uri.RDFS["LITERAL"])
both return "http://www.w3.org/2000/01/rdf-schema#Literal"
*/
uri.RDFS = { NS: "http://www.w3.org/2000/01/rdf-schema#" }
uri.RDFS = {
    NS: uri.RDFS.NS, // else it is overwritten
    // entities
    CLASS: `${uri.RDFS.NS}Class`,
    CONTAINER: `${uri.RDFS.NS}Container`,
    CONTAINERMEMBERSHIPPROPERTY: `${uri.RDFS.NS}ContainerMembershipProperty`,
    DATATYPE: `${uri.RDFS.NS}Datatype`,
    LITERAL: `${uri.RDFS.NS}Literal`,
    RESOURCE: `${uri.RDFS.NS}Resource`,
    // properties
    COMMENT: `${uri.RDFS.NS}comment`,
    DOMAIN: `${uri.RDFS.NS}domain`,
    ISDEFINEDBY: `${uri.RDFS.NS}isDefinedBy`,
    LABEL: `${uri.RDFS.NS}label`,
    MEMBER: `${uri.RDFS.NS}member`,
    RANGE: `${uri.RDFS.NS}range`,
    SEEALSO: `${uri.RDFS.NS}seeAlso`,
    SUBCLASSOF: `${uri.RDFS.NS}subClassOf`,
    SUBPROPERTYOF: `${uri.RDFS.NS}subPropertyOf`
}

/*
uri.SKOS
usage: alert(uri.SKOS.CONCEPT) | alert(uri.SKOS["CONCEPT"])
both return "http://www.w3.org/2004/02/skos/core#Concept" 
*/       
uri.SKOS = { NS: "http://www.w3.org/2004/02/skos/core#" }
uri.SKOS = {
    NS: uri.SKOS.NS, // else it is overwritten
    // entities
    COLLECTABLEPROPERTY: `${uri.SKOS.NS}CollectableProperty`,
    COLLECTION: `${uri.SKOS.NS}Collection`,
    CONCEPT: `${uri.SKOS.NS}Concept`,
    CONCEPTSCHEME: `${uri.SKOS.NS}ConceptScheme`,
    ORDEREDCOLLECTION: `${uri.SKOS.NS}OrderedCollection`,
    // properties
    ALTLABEL: `${uri.SKOS.NS}altLabel`,
    ALTSYMBOL: `${uri.SKOS.NS}altSymbol`,
    BROADER: `${uri.SKOS.NS}broader`,
    CHANGENOTE: `${uri.SKOS.NS}changeNote`,
    DEFINITION: `${uri.SKOS.NS}definition`,
    EDITORIALNOTE: `${uri.SKOS.NS}editorialNote`,
    EXAMPLE: `${uri.SKOS.NS}example`,
    HASTOPCONCEPT: `${uri.SKOS.NS}hasTopConcept`,
    HIDDENLABEL: `${uri.SKOS.NS}hiddenLabel`,
    HISTORYNOTE: `${uri.SKOS.NS}historyNote`,
    INSCHEME: `${uri.SKOS.NS}inScheme`,
    ISPRIMARYSUBJECTOF: `${uri.SKOS.NS}isPrimarySubjectOf`,
    ISSUBJECTOF: `${uri.SKOS.NS}isSubjectOf`,
    MEMBER: `${uri.SKOS.NS}member`,
    MEMBERLIST: `${uri.SKOS.NS}memberList`,
    NARROWER: `${uri.SKOS.NS}narrower`,
    NOTE: `${uri.SKOS.NS}note`,
    PREFLABEL: `${uri.SKOS.NS}prefLabel`,
    PREFSYMBOL: `${uri.SKOS.NS}prefSymbol`,
    PRIMARYSUBJECT: `${uri.SKOS.NS}primarySubject`,
    RELATED: `${uri.SKOS.NS}related`,
    SCOPENOTE: `${uri.SKOS.NS}scopeNote`,
    SEMANTICRELATION: `${uri.SKOS.NS}semanticRelation`,
    SUBJECT: `${uri.SKOS.NS}subject`,
    SUBJECTINDICATOR: `${uri.SKOS.NS}subjectIndicator`,
    SYMBOL: `${uri.SKOS.NS}symbol`,
    // mapping properties
    BROADMATCH: `${uri.SKOS.NS}broadMatch`,
    CLOSEMATCH: `${uri.SKOS.NS}closeMatch`,
    EXACTMATCH: `${uri.SKOS.NS}exactMatch`,
    NARROWMATCH: `${uri.SKOS.NS}narrowMatch`,
    RELATEDMATCH: `${uri.SKOS.NS}relatedMatch`
}

/*
uri.SKOSXL
usage: alert(uri.SKOSXL.PREFLABEL) | alert(uri.SKOSXL["PREFLABEL"])
both return "http://www.w3.org/2008/05/skos-xl#Label"
*/        
uri.SKOSXL = { NS: "http://www.w3.org/2008/05/skos-xl#" }
uri.SKOSXL = {
    NS: uri.SKOSXL.NS, // else it is overwritten
    // entities
    LABEL: `${uri.SKOSXL.NS}Label`,
    // properties
    ALTLABEL: `${uri.SKOSXL.NS}altLabel`,
    HIDDENLABEL: `${uri.SKOSXL.NS}hiddenLabel`,
    LABELRELATION: `${uri.SKOSXL.NS}labelRelation`,
    LITERALFORM: `${uri.SKOSXL.NS}literalForm`,
    PREFLABEL: `${uri.SKOSXL.NS}prefLabel`
}

/*
uri.CRMEH
usage: alert(uri.CRMEH.EHE0001) | alert(uri.CRMEH["EHE0001"])
both return "http://purl.org/crmeh#EHE0001_EHProject"    
*/
uri.CRMEH = { NS: "http://purl.org/crmeh#" }
uri.CRMEH = {
    NS: uri.CRMEH.NS, // else it is overwritten
    // entities
    EHE0001: `${uri.CRMEH.NS}EHE0001_EHProject`,
    EHE0002: `${uri.CRMEH.NS}EHE0002_ArchaeologicalSite`,
    EHE0003: `${uri.CRMEH.NS}EHE0003_AreaOfInvestigation`,
    EHE0004: `${uri.CRMEH.NS}EHE0004_SiteSubDivision`,
    EHE0005: `${uri.CRMEH.NS}EHE0005_Group`,
    EHE0006: `${uri.CRMEH.NS}EHE0006_GroupStuff`,
    EHE0007: `${uri.CRMEH.NS}EHE0007_Context`,
    EHE0008: `${uri.CRMEH.NS}EHE0008_ContextStuff`,
    EHE0009: `${uri.CRMEH.NS}EHE0009_ContextFind`,
    EHE0010: `${uri.CRMEH.NS}EHE0010_BulkFind`,
    EHE0011: `${uri.CRMEH.NS}EHE0011_GroupEventRecord`,
    EHE0012: `${uri.CRMEH.NS}EHE0012_ContextEventRecord`,
    EHE0013: `${uri.CRMEH.NS}EHE0013_ContextSheet`,
    EHE0014: `${uri.CRMEH.NS}EHE0014_ContextFindProductionEventRecord`,
    EHE0015: `${uri.CRMEH.NS}EHE0015_ContextFindUseEventRecord`,
    EHE0016: `${uri.CRMEH.NS}EHE0016_RecordDrawing`,
    EHE0017: `${uri.CRMEH.NS}EHE0017_RecordPhotograph`,
    EHE0018: `${uri.CRMEH.NS}EHE0018_ContextSample`,
    EHE0019: `${uri.CRMEH.NS}EHE0019_AreaOfInvestigationDepiction`,
    EHE0020: `${uri.CRMEH.NS}EHE0020_BulkFindComponentCount`,
    EHE0021: `${uri.CRMEH.NS}EHE0021_EHProjectTimespan`,
    EHE0022: `${uri.CRMEH.NS}EHE0022_ContextDepiction`,
    EHE0023: `${uri.CRMEH.NS}EHE0023_ContextEventRecordNote`,
    EHE0024: `${uri.CRMEH.NS}EHE0024_ContextEventRecordNoteType`,
    EHE0025: `${uri.CRMEH.NS}EHE0025_ContextEventTimespan`,
    EHE0026: `${uri.CRMEH.NS}EHE0026_ContextEventTimespanAppellation`,
    EHE0027: `${uri.CRMEH.NS}EHE0027_ContextFindConditionAssessmentEventTimespan`,
    EHE0028: `${uri.CRMEH.NS}EHE0028_ContextFindConditionAssessmentEventType`,
    EHE0029: `${uri.CRMEH.NS}EHE0029_ContextFindConditionState`,
    EHE0030: `${uri.CRMEH.NS}EHE0030_ContextFindMaterial`,
    EHE0031: `${uri.CRMEH.NS}EHE0031_ContextFindMeasurement`,
    EHE0032: `${uri.CRMEH.NS}EHE0032_ContextFindMeasurementEventTimespan`,
    EHE0033: `${uri.CRMEH.NS}EHE0033_ContextFindMeasurementEventType`,
    EHE0034: `${uri.CRMEH.NS}EHE0034_ContextFindMeasurementUnit`,
    EHE0035: `${uri.CRMEH.NS}EHE0035_ContextFindMeasurementValue`,
    EHE0036: `${uri.CRMEH.NS}EHE0036_ContextFindProductionEventRecordNote`,
    EHE0037: `${uri.CRMEH.NS}EHE0037_ContextFindProductionEventRecordNoteType`,
    EHE0038: `${uri.CRMEH.NS}EHE0038_ContextFindProductionEventTimespan`,
    EHE0039: `${uri.CRMEH.NS}EHE0039_ContextFindProductionEventTimespanAppellation`,
    EHE0040: `${uri.CRMEH.NS}EHE0040_ContextFindTreatmentLocation`,
    EHE0041: `${uri.CRMEH.NS}EHE0041_ContextFindTreatmentProcedure`,
    EHE0042: `${uri.CRMEH.NS}EHE0042_ContextFindTreatmentType`,
    EHE0043: `${uri.CRMEH.NS}EHE0043_ContextFindUID`,
    EHE0044: `${uri.CRMEH.NS}EHE0044_ContextFindUseEventRecordNote`,
    EHE0045: `${uri.CRMEH.NS}EHE0045_ContextFindUseEventRecordNoteType`,
    EHE0046: `${uri.CRMEH.NS}EHE0046_ContextNote`,
    EHE0047: `${uri.CRMEH.NS}EHE0047_ContextNoteType`,
    EHE0048: `${uri.CRMEH.NS}EHE0048_ContextRecord`,
    EHE0049: `${uri.CRMEH.NS}EHE0049_ContextSampleMeasurement`,
    EHE0050: `${uri.CRMEH.NS}EHE0050_ContextSampleMeasurementType`,
    EHE0051: `${uri.CRMEH.NS}EHE0051_ContextSampleMeasurementUnit`,
    EHE0052: `${uri.CRMEH.NS}EHE0052_ContextSampleMeasurementValue`,
    EHE0053: `${uri.CRMEH.NS}EHE0053_ContextSampleType`,
    EHE0054: `${uri.CRMEH.NS}EHE0054_ContextStuffMeasurement`,
    EHE0055: `${uri.CRMEH.NS}EHE0055_ContextStuffMeasurementEventTimespan`,
    EHE0056: `${uri.CRMEH.NS}EHE0056_ContextStuffMeasurementEventType`,
    EHE0057: `${uri.CRMEH.NS}EHE0057_ContextStuffMeasurementUnit`,
    EHE0058: `${uri.CRMEH.NS}EHE0058_ContextStuffMeasurementValue`,
    EHE0059: `${uri.CRMEH.NS}EHE0059_ContextStuffNote`,
    EHE0060: `${uri.CRMEH.NS}EHE0060_ContextStuffNoteType`,
    EHE0061: `${uri.CRMEH.NS}EHE0061_ContextUID`,
    EHE0062: `${uri.CRMEH.NS}EHE0062_FlotationSample`,
    EHE0063: `${uri.CRMEH.NS}EHE0063_FlotationSampleResidue`,
    EHE0064: `${uri.CRMEH.NS}EHE0064_FlotationSampleResidueMeasurement`,
    EHE0065: `${uri.CRMEH.NS}EHE0065_FlotationSampleResidueMeasurementUnit`,
    EHE0066: `${uri.CRMEH.NS}EHE0066_FlotationSampleResidueMeasurementValue`,
    EHE0067: `${uri.CRMEH.NS}EHE0067.FlotationSampleResidueType`,
    EHE0068: `${uri.CRMEH.NS}EHE0068_GroupEventRecordNote`,
    EHE0069: `${uri.CRMEH.NS}EHE0069_GroupEventRecordNoteType`,
    EHE0070: `${uri.CRMEH.NS}EHE0070_GroupEventTimespan`,
    EHE0071: `${uri.CRMEH.NS}EHE0071_GroupEventTimespanAppellation`,
    EHE0072: `${uri.CRMEH.NS}EHE0072_GroupEventType`,
    EHE0073: `${uri.CRMEH.NS}EHE0073_GroupingPhasingProcedure`,
    EHE0074: `${uri.CRMEH.NS}EHE0074_IdentifiedFeature`,
    EHE0075: `${uri.CRMEH.NS}EHE0075_IdentifiedFeatureDepiction`,
    EHE0076: `${uri.CRMEH.NS}EHE0076_ProjectDesign`,
    EHE0077: `${uri.CRMEH.NS}EHE0077_ProjectTeamMember`,
    EHE0078: `${uri.CRMEH.NS}EHE0078_ProjectTeamMemberRole`,
    EHE0079: `${uri.CRMEH.NS}EHE0079_RecordDrawingNote`,
    EHE0080: `${uri.CRMEH.NS}EHE0080_RecordDrawingNoteType`,
    EHE0081: `${uri.CRMEH.NS}EHE0081_RecordDrawingReferenceType`,
    EHE0082: `${uri.CRMEH.NS}EHE0082_RecordDrawingSheet`,
    EHE0083: `${uri.CRMEH.NS}EHE0083_RecordPhotographNote`,
    EHE0084: `${uri.CRMEH.NS}EHE0084_RecordPhotographNoteType`,
    EHE0085: `${uri.CRMEH.NS}EHE0085_RecordPhotographReferenceType`,
    EHE0086: `${uri.CRMEH.NS}EHE0086_ResponsibleAgent`,
    EHE0087: `${uri.CRMEH.NS}EHE0087_SiteSubDivisionAppellation`,
    EHE0088: `${uri.CRMEH.NS}EHE0088_SiteSubDivisionDepiction`,
    EHE0089: `${uri.CRMEH.NS}EHE0089_StorageLocation`,
    EHE0090: `${uri.CRMEH.NS}EHE0090_SurveyDataset`,
    EHE0091: `${uri.CRMEH.NS}EHE0091_Timestamp`,
    EHE0092: `${uri.CRMEH.NS}EHE0092_GroupUID`,
    EHE0093: `${uri.CRMEH.NS}EHE0093_GroupDepiction`,
    EHE0094: `${uri.CRMEH.NS}EHE0094_FlotationSampleResidueMeasurementType`,
    EHE0095: `${uri.CRMEH.NS}EHE0095_ContextFindProductionEventLocation`,
    EHE0096: `${uri.CRMEH.NS}EHE0096_ContextFindGeneralUse`,
    EHE0097: `${uri.CRMEH.NS}EHE0097_ContextFindIntendedUse`,
    EHE0098: `${uri.CRMEH.NS}EHE0098_ContextFindExcavationEventTimespan`,
    EHE0099: `${uri.CRMEH.NS}EHE0099_ContextFindUseEventTimespan`,
    EHE1001: `${uri.CRMEH.NS}EHE1001_ContextEvent`,
    EHE1002: `${uri.CRMEH.NS}EHE1002_ContextFindProductionEvent`,
    EHE1003: `${uri.CRMEH.NS}EHE1003_GroupEvent`,
    EHE1004: `${uri.CRMEH.NS}EHE1004_ContextFindDepositionEvent`,
    EHE1005: `${uri.CRMEH.NS}EHE1005_ContextFindUseEvent`,
    EHE2001: `${uri.CRMEH.NS}EHE2001_ContextExcavationEvent`,
    EHE2002: `${uri.CRMEH.NS}EHE2002_ContextFindClassificationEvent`,
    EHE2003: `${uri.CRMEH.NS}EHE2003_ContextFindTreatmentEvent`,
    EHE2004: `${uri.CRMEH.NS}EHE2004_GroupingPhasingEvent`,
    EHE2005: `${uri.CRMEH.NS}EHE2005_ContextFindDatingEvent`,
    EHE2006: `${uri.CRMEH.NS}EHE2006_ContextSamplingEvent`,
    EHE2007: `${uri.CRMEH.NS}EHE2007_SurveyEvent`,
    EHE2008: `${uri.CRMEH.NS}EHE2008_ProcessSurveyDatasetEvent`,
    EHE2009: `${uri.CRMEH.NS}EHE2009_TransferObjectEvent`,
    EHE2010: `${uri.CRMEH.NS}EHE2010_DepictionEvent`,
    EHE2011: `${uri.CRMEH.NS}EHE2011_BulkFindItemRemovalEvent`,
    EHE2012: `${uri.CRMEH.NS}EHE2012_ContextFindConditionAssessmentEvent`,
    EHE2013: `${uri.CRMEH.NS}EHE2013_ContextFindIdentifierAssignmentEvent`,
    EHE2014: `${uri.CRMEH.NS}EHE2014_ContextFindUseAssessmentEvent`,
    EHE2015: `${uri.CRMEH.NS}EHE2015_ContextSampleProcessingEvent`,
    EHE2016: `${uri.CRMEH.NS}EHE2016_ContextStuffMeasurementEvent`,
    EHE2017: `${uri.CRMEH.NS}EHE2017_FlotationSampleProcessingEvent`,
    EHE2018: `${uri.CRMEH.NS}EHE2018_FlotationSampleResidueProcessingEvent`,
    EHE2019: `${uri.CRMEH.NS}EHE2019_SimpleNameAssignmentEvent`,
    EHE2020: `${uri.CRMEH.NS}EHE2020_ContextFindMeasurementEvent`,
    EHE2021: `${uri.CRMEH.NS}EHE2021_BulkFindAssessment`,
    // properties
    EHP1F: `${uri.CRMEH.NS}EHP1F_is_trace_of`,
    EHP2F: `${uri.CRMEH.NS}EHP2F_is_trace_of_type`,
    EHP3B: `${uri.CRMEH.NS}EHP3B_was_occupied_by`,
    EHP3F: `${uri.CRMEH.NS}EHP3F_occupied`,
    EHP4B: `${uri.CRMEH.NS}EHP4B_is_depicted_by`,
    EHP4F: `${uri.CRMEH.NS}EHP4F_depicts`,
    EHP5F: `${uri.CRMEH.NS}EHP5F_is_thesaurus_concept`,
    EHP1003B: `${uri.CRMEH.NS}EHP1003B_is_note_of`,
    EXP1F: `${uri.CRMEH.NS}EXP1F_year_min`,
    EXP2F: `${uri.CRMEH.NS}EXP2F_year_max`,
    EXP3F: `${uri.CRMEH.NS}EXP3F_spatial_x`,
    EXP4F: `${uri.CRMEH.NS}EXP4F_spatial_y`,
    EXP5F: `${uri.CRMEH.NS}EXP5F_spatial_z`,
    EXP10F: `${uri.CRMEH.NS}EXP10F_is_represented_by`
}

/*
uri.DC - Dublin Core elements
usage: alert(uri.DC.TITLE) | alert(uri.DC["TITLE"])
both return "http://purl.org/dc/elements/1.1/title" 
*/ 
uri.DC = { NS: "http://purl.org/dc/elements/1.1/" }
uri.DC = {
    NS: uri.DC.NS, // else it is overwritten
    // properties
    CONTRIBUTOR: `${uri.DC.NS}contributor`,
    COVERAGE: `${uri.DC.NS}coverage`,
    CREATOR: `${uri.DC.NS}creator`,
    DATE: `${uri.DC.NS}date`,
    DESCRIPTION: `${uri.DC.NS}description`,
    FORMAT: `${uri.DC.NS}format`,
    IDENTIFIER: `${uri.DC.NS}identifier`,
    LANGUAGE: `${uri.DC.NS}language`,
    PUBLISHER: `${uri.DC.NS}publisher`,
    RELATION: `${uri.DC.NS}relation`,
    RIGHTS: `${uri.DC.NS}rights`,
    SOURCE: `${uri.DC.NS}source`,
    SUBJECT: `${uri.DC.NS}subject`,
    TITLE: `${uri.DC.NS}title`,
    TYPE: `${uri.DC.NS}type`
}

/*
uri.DCTERMS - Dublin Core terms
usage: alert(uri.DCTERMS.SUBJECTSCHEME) | alert(uri.DCTERMS["SUBJECTSCHEME"])
both return "http://purl.org/dc/terms/SubjectScheme"  
*/   
uri.DCTERMS = { NS: "http://purl.org/dc/terms/" }
uri.DCTERMS = {
    NS: uri.DCTERMS.NS, // else it is overwritten
    // entities
    DATESCHEME: `${uri.DCTERMS.NS}DateScheme`,
    FORMATSCHEME: `${uri.DCTERMS.NS}FormatScheme`,
    IDENTIFIERSCHEME: `${uri.DCTERMS.NS}IdentifierScheme`,
    LANGUAGESCHEME: `${uri.DCTERMS.NS}LanguageScheme`,
    RELATIONSCHEME: `${uri.DCTERMS.NS}RelationScheme`,
    SOURCESCHEME: `${uri.DCTERMS.NS}SourceScheme`,
    SPATIALSCHEME: `${uri.DCTERMS.NS}SpatialScheme`,
    SUBJECTSCHEME: `${uri.DCTERMS.NS}SubjectScheme`,
    TEMPORALSCHEME: `${uri.DCTERMS.NS}TemporalScheme`,
    TYPESCHEME: `${uri.DCTERMS.NS}TypeScheme`,
    // properties 
    ABSTRACT: `${uri.DCTERMS.NS}abstract`,
    ACCESSRIGHTS: `${uri.DCTERMS.NS}accessRights`,
    ACCRUALMETHOD: `${uri.DCTERMS.NS}accrualMethod`,
    ACCRUALPERIODICITY: `${uri.DCTERMS.NS}accrualPeriodicity`,
    ACCRUALPOLICY: `${uri.DCTERMS.NS}accrualPolicy`,
    ALTERNATIVE: `${uri.DCTERMS.NS}alternative`,
    AUDIENCE: `${uri.DCTERMS.NS}audience`,
    AVAILABLE: `${uri.DCTERMS.NS}available`,
    BIBLIOGRAPHICCITATION: `${uri.DCTERMS.NS}bibliographicCitation`,
    CONFORMSTO: `${uri.DCTERMS.NS}conformsTo`,
    CONTRIBUTOR: `${uri.DCTERMS.NS}contributor`, 
    COVERAGE: `${uri.DCTERMS.NS}coverage`, 
    CREATED: `${uri.DCTERMS.NS}created`,
    CREATOR: `${uri.DCTERMS.NS}creator`, 
    DATE: `${uri.DCTERMS.NS}date`, 
    DATEACCEPTED: `${uri.DCTERMS.NS}dateAccepted`,
    DATECOPYRIGHTED: `${uri.DCTERMS.NS}dateCopyrighted`,
    DATESUBMITTED: `${uri.DCTERMS.NS}dateSubmitted`,
    DESCRIPTION: `${uri.DCTERMS.NS}description`, 
    EDUCATIONLEVEL: `${uri.DCTERMS.NS}educationLevel`,
    EXTENT: `${uri.DCTERMS.NS}extent`,
    FORMAT: `${uri.DCTERMS.NS}format`, 
    HASFORMAT: `${uri.DCTERMS.NS}hasFormat`,
    HASPART: `${uri.DCTERMS.NS}hasPart`,
    HASVERSION: `${uri.DCTERMS.NS}hasVersion`,
    IDENTIFIER: `${uri.DCTERMS.NS}identifier`,
    INSTRUCTIONALMETHOD: `${uri.DCTERMS.NS}instructionalMethod`,
    ISFORMATOF: `${uri.DCTERMS.NS}isFormatOf`,
    ISPARTOF: `${uri.DCTERMS.NS}isPartOf`,
    ISREFERENCEDBY: `${uri.DCTERMS.NS}isReferencedBy`,
    ISREPLACEDBY: `${uri.DCTERMS.NS}isReplacedBy`,
    ISREQUIREDBY: `${uri.DCTERMS.NS}isRequiredBy`,
    ISSUED: `${uri.DCTERMS.NS}issued`,
    ISVERSIONOF: `${uri.DCTERMS.NS}isVersionOf`,
    LANGUAGE: `${uri.DCTERMS.NS}language`, 
    LICENSE: `${uri.DCTERMS.NS}license`,
    MEDIATOR: `${uri.DCTERMS.NS}mediator`,
    MEDIUM: `${uri.DCTERMS.NS}medium`,
    MODIFIED: `${uri.DCTERMS.NS}modified`,
    PROVENANCE: `${uri.DCTERMS.NS}provenance`,
    PUBLISHER: `${uri.DCTERMS.NS}publisher`,
    REFERENCES: `${uri.DCTERMS.NS}references`,
    RELATION: `${uri.DCTERMS.NS}relation`,
    REPLACES: `${uri.DCTERMS.NS}replaces`,
    REQUIRES: `${uri.DCTERMS.NS}requires`,
    RIGHTS: `${uri.DCTERMS.NS}rights`,
    RIGHTSHOLDER: `${uri.DCTERMS.NS}rightsHolder`,
    SOURCE: `${uri.DCTERMS.NS}source`, //new
    SPATIAL: `${uri.DCTERMS.NS}spatial`,
    SUBJECT: `${uri.DCTERMS.NS}subject`,
    TABLEOFCONTENTS: `${uri.DCTERMS.NS}tableOfContents`,
    TEMPORAL: `${uri.DCTERMS.NS}temporal`,
    TITLE: `${uri.DCTERMS.NS}title`,
    TYPE: `${uri.DCTERMS.NS}type`,
    VALID: `${uri.DCTERMS.NS}valid`,
    // Vocabulary Encoding Schemes
    DCMITYPE: `${uri.DCTERMS.NS}DCMIType`,
    DDC: `${uri.DCTERMS.NS}DDC`,
    IMT: `${uri.DCTERMS.NS}IMT`,
    LCC: `${uri.DCTERMS.NS}LCC`,
    LCSH: `${uri.DCTERMS.NS}LCSH`,
    MESH: `${uri.DCTERMS.NS}MESH`,
    NLM: `${uri.DCTERMS.NS}NLM`,
    TGN: `${uri.DCTERMS.NS}TGN`,
    UDC: `${uri.DCTERMS.NS}UDC`,
    // Syntax Encoding Schemes
    BOX: `${uri.DCTERMS.NS}Box`,
    ISO3166: `${uri.DCTERMS.NS}ISO3166`,
    ISO6392: `${uri.DCTERMS.NS}ISO639-2`,
    ISO6393: `${uri.DCTERMS.NS}ISO639-3`,
    PERIOD: `${uri.DCTERMS.NS}Period`,
    POINT: `${uri.DCTERMS.NS}Point`,
    RFC1766: `${uri.DCTERMS.NS}RFC1766`,
    RFC3066: `${uri.DCTERMS.NS}RFC3066`,
    RFC4646: `${uri.DCTERMS.NS}RFC4646`,
    RFC5646: `${uri.DCTERMS.NS}RFC5646`,
    URI: `${uri.DCTERMS.NS}URI`,
    W3CDTF: `${uri.DCTERMS.NS}W3CDTF`
}

/*
uri.DCMI - DCMI Type Vocabulary
usage: alert(uri.DCMI.COLLECTION) | alert(uri.DCMI["COLLECTION"])
both return "http://purl.org/dc/dcmitype/Collection" 
*/
uri.DCMI = { NS: "http://purl.org/dc/dcmitype/" }
uri.DCMI = {
    NS: uri.DCMI.NS, // else it is overwritten
    COLLECTION: `${uri.DCMI.NS}Collection`,
    DATASET: `${uri.DCMI.NS}Dataset`,
    EVENT: `${uri.DCMI.NS}Event`,
    IMAGE: `${uri.DCMI.NS}Image`,
    INTERACTIVERESOURCE: `${uri.DCMI.NS}InteractiveResource`,
    MOVINGIMAGE: `${uri.DCMI.NS}MovingImage`,
    PHYSICALOBJECT: `${uri.DCMI.NS}PhysicalObject`,
    SERVICE: `${uri.DCMI.NS}Service`,
    SOFTWARE: `${uri.DCMI.NS}Software`,
    SOUND: `${uri.DCMI.NS}Sound`,
    STILLIMAGE: `${uri.DCMI.NS}StillImage`,
    TEXT: `${uri.DCMI.NS}Text`
}

/*
uri.DCAM - Dublin Core Abstract Model
usage: alert(uri.DCAM.MEMBEROF) | alert(uri.DCAM["MEMBEROF"])
both return "http://purl.org/dc/dcam/memberOf" 
*/  
uri.DCAM = { NS: "http://purl.org/dc/dcam/" }
uri.DCAM = {
    NS: uri.DCAM.NS, // else it is overwritten
    // entities
    VOCABULARYENCODINGSCHEME: `${uri.DCAM.NS}VocabularyEncodingScheme`,
    // properties
    MEMBEROF: `${uri.DCAM.NS}memberOf`
}

/*
uri.OWL
usage: alert(uri.OWL.ALLDIFFERENT) | alert(uri.OWL["ALLDIFFERENT"])
both return "http://www.w3.org/2002/07/owl#AllDifferent" 
*/
uri.OWL = { NS: "http://www.w3.org/2002/07/owl#" }
uri.OWL = {
    NS: uri.OWL.NS, // else it is overwritten
    // entities
    ALLDIFFERENT: `${uri.OWL.NS}AllDifferent`,
    ANNOTATIONPROPERTY: `${uri.OWL.NS}AnnotationProperty`,
    CLASS: `${uri.OWL.NS}Class`,
    DATARANGE: `${uri.OWL.NS}DataRange`,
    DATATYPEPROPERTY: `${uri.OWL.NS}DatatypeProperty`,
    DEPRECATEDCLASS: `${uri.OWL.NS}DeprecatedClass`,
    DEPRECATEDPROPERTY: `${uri.OWL.NS}DeprecatedProperty`,
    FUNCTIONALPROPERTY: `${uri.OWL.NS}FunctionalProperty`,
    INVERSEFUNCTIONALPROPERTY: `${uri.OWL.NS}InverseFunctionalProperty`,
    NOTHING: `${uri.OWL.NS}Nothing`,
    OBJECTPROPERTY: `${uri.OWL.NS}ObjectProperty`,
    ONTOLOGY: `${uri.OWL.NS}Ontology`,
    ONTOLOGYPROPERTY: `${uri.OWL.NS}OntologyProperty`,
    RESTRICTION: `${uri.OWL.NS}Restriction`,
    SYMMETRICPROPERTY: `${uri.OWL.NS}SymmetricProperty`,
    THING: `${uri.OWL.NS}Thing`,
    TRANSITIVEPROPERTY: `${uri.OWL.NS}TransitiveProperty`,
    // properties
    ALLVALUESFROM: `${uri.OWL.NS}allValuesFrom`,
    BACKWARDCOMPATIBLEWITH: `${uri.OWL.NS}backwardCompatibleWith`,
    CARDINALITY: `${uri.OWL.NS}cardinality`,
    COMPLEMENTOF: `${uri.OWL.NS}complementOf`,
    DIFFERENTFROM: `${uri.OWL.NS}differentFrom`,
    DISJOINTWITH: `${uri.OWL.NS}disjointWith`,
    DISTINCTMEMBERS: `${uri.OWL.NS}distinctMembers`,
    EQUIVALENTCLASS: `${uri.OWL.NS}equivalentClass`,
    EQUIVALENTPROPERTY: `${uri.OWL.NS}equivalentProperty`,
    HASVALUE: `${uri.OWL.NS}hasValue`,
    IMPORTS: `${uri.OWL.NS}imports`,
    INCOMPATIBLEWITH: `${uri.OWL.NS}incompatibleWith`,
    INTERSECTIONOF: `${uri.OWL.NS}intersectionOf`,
    INVERSEOF: `${uri.OWL.NS}inverseOf`,
    MAXCARDINALITY: `${uri.OWL.NS}maxCardinality`,
    MINCARDINALITY: `${uri.OWL.NS}minCardinality`,
    ONEOF: `${uri.OWL.NS}oneOf`,
    ONPROPERTY: `${uri.OWL.NS}onProperty`,
    PRIORVERSION: `${uri.OWL.NS}priorVersion`,
    SAMEAS: `${uri.OWL.NS}sameAs`,
    SOMEVALUESFROM: `${uri.OWL.NS}someValuesFrom`,
    UNIONOF: `${uri.OWL.NS}unionOf`,
    VERSIONINFO: `${uri.OWL.NS}versionInfo`
}

/*
uri.CRM - represents version 5.0.4 of CIDOC CRM
usage: alert(uri.CRM.E1) | alert(uri.CRM["E1"])
both return "http://www.cidoc-crm.org/cidoc-crm/E1_CRM_Entity" 
*/
uri.CRM = { NS: "http://www.cidoc-crm.org/cidoc-crm/" }
uri.CRM = {
    NS: uri.CRM.NS, // else it is overwritten
    // entities
    E1: `${uri.CRM.NS}E1_CRM_Entity`,
    E2: `${uri.CRM.NS}E2_Temporal_Entity`,
    E3: `${uri.CRM.NS}E3_Condition_State`,
    E4: `${uri.CRM.NS}E4_Period`,
    E5: `${uri.CRM.NS}E5_Event`,
    E6: `${uri.CRM.NS}E6_Destruction`,
    E7: `${uri.CRM.NS}E7_Activity`,
    E8: `${uri.CRM.NS}E8_Acquisition`,
    E9: `${uri.CRM.NS}E9_Move`,
    E10: `${uri.CRM.NS}E10_Transfer_of_Custody`,
    E11: `${uri.CRM.NS}E11_Modification`,
    E12: `${uri.CRM.NS}E12_Production`,
    E13: `${uri.CRM.NS}E13_Attribute_Assignment`,
    E14: `${uri.CRM.NS}E14_Condition_Assessment`,
    E15: `${uri.CRM.NS}E15_Identifier_Assignment`,
    E16: `${uri.CRM.NS}E16_Measurement`,
    E17: `${uri.CRM.NS}E17_Type_Assignment`,
    E18: `${uri.CRM.NS}E18_Physical_Thing`,
    E19: `${uri.CRM.NS}E19_Physical_Object`,
    E20: `${uri.CRM.NS}E20_Biological_Object`,
    E21: `${uri.CRM.NS}E21_Person`,
    E22: `${uri.CRM.NS}E22_Man-Made_Object`,
    E24: `${uri.CRM.NS}E24_Physical_Man-Made_Thing`,
    E25: `${uri.CRM.NS}E25_Man-Made_Feature`,
    E26: `${uri.CRM.NS}E26_Physical_Feature`,
    E27: `${uri.CRM.NS}E27_Site`,
    E28: `${uri.CRM.NS}E28_Conceptual_Object`,
    E29: `${uri.CRM.NS}E29_Design_or_Procedure`,
    E30: `${uri.CRM.NS}E30_Right`,
    E31: `${uri.CRM.NS}E31_Document`,
    E32: `${uri.CRM.NS}E32_Authority_Document`,
    E33: `${uri.CRM.NS}E33_Linguistic_Object`,
    E34: `${uri.CRM.NS}E34_Inscription`,
    E35: `${uri.CRM.NS}E35_Title`,
    E36: `${uri.CRM.NS}E36_Visual_Item`,
    E37: `${uri.CRM.NS}E37_Mark`,
    E38: `${uri.CRM.NS}E38_Image`,
    E39: `${uri.CRM.NS}E39_Actor`,
    E40: `${uri.CRM.NS}E40_Legal_Body`,
    E41: `${uri.CRM.NS}E41_Appellation`,
    E42: `${uri.CRM.NS}E42_Identifier`,
    E44: `${uri.CRM.NS}E44_Place_Appellation`,
    E45: `${uri.CRM.NS}E45_Address`,
    E46: `${uri.CRM.NS}E46_Section_Definition`,
    E47: `${uri.CRM.NS}E47_Spatial_Coordinates`,
    E48: `${uri.CRM.NS}E48_Place_Name`,
    E49: `${uri.CRM.NS}E49_Time_Appellation`,
    E50: `${uri.CRM.NS}E50_Date`,
    E51: `${uri.CRM.NS}E51_Contact_Point`,
    E52: `${uri.CRM.NS}E52_Time-Span`,
    E53: `${uri.CRM.NS}E53_Place`,
    E54: `${uri.CRM.NS}E54_Dimension`,
    E55: `${uri.CRM.NS}E55_Type`,
    E56: `${uri.CRM.NS}E56_Language`,
    E57: `${uri.CRM.NS}E57_Material`,
    E58: `${uri.CRM.NS}E58_Measurement_Unit`,
    E59: `${uri.CRM.NS}E59_PrimitiveValue`,
    E60: `${uri.CRM.NS}E60_Number`,
    E61: `${uri.CRM.NS}E61_Time_Primitive`,
    E62: `${uri.CRM.NS}E62_String`,
    E63: `${uri.CRM.NS}E63_Beginning_of_Existence`,
    E64: `${uri.CRM.NS}E64_End_of_Existence`,
    E65: `${uri.CRM.NS}E65_Creation`,
    E66: `${uri.CRM.NS}E66_Formation`,
    E67: `${uri.CRM.NS}E67_Birth`,
    E68: `${uri.CRM.NS}E68_Dissolution`,
    E69: `${uri.CRM.NS}E69_Death`,
    E70: `${uri.CRM.NS}E70_Thing`,
    E71: `${uri.CRM.NS}E71_Man-Made_Thing`,
    E72: `${uri.CRM.NS}E72_Legal_Object`,
    E73: `${uri.CRM.NS}E73_Information_Object`,
    E74: `${uri.CRM.NS}E74_Group`,
    E75: `${uri.CRM.NS}E75_Conceptual_Object_Appellation`,
    E77: `${uri.CRM.NS}E77_Persistent_Item`,
    E78: `${uri.CRM.NS}E78_Collection`,
    E79: `${uri.CRM.NS}E79_Part_Addition`,
    E80: `${uri.CRM.NS}E80_Part_Removal`,
    E81: `${uri.CRM.NS}E81_Transformation`,
    E82: `${uri.CRM.NS}E82_Actor_Appellation`,
    E83: `${uri.CRM.NS}E83_Type_Creation`,
    E84: `${uri.CRM.NS}E84_Information_Carrier`,
    E85: `${uri.CRM.NS}E85_Joining`,
    E86: `${uri.CRM.NS}E86_Leaving`,
    E87: `${uri.CRM.NS}E87_Curation_Activity`,
    E89: `${uri.CRM.NS}E89_Propositional_Object`,
    E90: `${uri.CRM.NS}E90_Symbolic_Object`,
    // properties
    P1: `${uri.CRM.NS}P1_is_identified_by`,
    P1i: `${uri.CRM.NS}P1i_identifies`,
    P2: `${uri.CRM.NS}P2_has_type`,
    P2i: `${uri.CRM.NS}P2i_is_type_of`,
    P3: `${uri.CRM.NS}P3_has_note`,
    P4: `${uri.CRM.NS}P4_has_time-span`,
    P4i: `${uri.CRM.NS}P4i_is_time-span_of`,
    P5: `${uri.CRM.NS}P5_consists_of`,
    P5i: `${uri.CRM.NS}P5i_forms_part_of`,
    P7: `${uri.CRM.NS}P7_took_place_at`,
    P7i: `${uri.CRM.NS}P7i_witnessed`,
    P8: `${uri.CRM.NS}P8_took_place_on_or_within`,
    P8i: `${uri.CRM.NS}P8i_witnessed`,
    P9: `${uri.CRM.NS}P9_consists_of`,
    P9i: `${uri.CRM.NS}P9i_forms_part_of`,
    P10: `${uri.CRM.NS}P10_falls_within`,
    P10i: `${uri.CRM.NS}P10i_contains`,
    P11: `${uri.CRM.NS}P11_had_participant`,
    P11i: `${uri.CRM.NS}P11i_participated_in`,
    P12: `${uri.CRM.NS}P12_occurred_in_the_presence_of`,
    P12i: `${uri.CRM.NS}P12i_was_present_at`,
    P13: `${uri.CRM.NS}P13_destroyed`,
    P13i: `${uri.CRM.NS}P13i_was_destroyed_by`,
    P14: `${uri.CRM.NS}P14_carried_out_by`,
    P14i: `${uri.CRM.NS}P14i_performed`,
    P15: `${uri.CRM.NS}P15_was_influenced_by`,
    P15i: `${uri.CRM.NS}P15i_influenced`,
    P16: `${uri.CRM.NS}P16_used_specific_object`,
    P16i: `${uri.CRM.NS}P16i_was_used_for`,
    P17: `${uri.CRM.NS}P17_was_motivated_by`,
    P17i: `${uri.CRM.NS}P17i_motivated`,
    P19: `${uri.CRM.NS}P19_was_intended_use_of`,
    P19i: `${uri.CRM.NS}P19i_was_made_for`,
    P20: `${uri.CRM.NS}P20_had_specific_purpose`,
    P20i: `${uri.CRM.NS}P20i_was_purpose_of`,
    P21: `${uri.CRM.NS}P21_had_general_purpose`,
    P21i: `${uri.CRM.NS}P21i_was_purpose_of`,
    P22: `${uri.CRM.NS}P22_transferred_title_to`,
    P22i: `${uri.CRM.NS}P22i_acquired_title_through`,
    P23: `${uri.CRM.NS}P23_transferred_title_from`,
    P23i: `${uri.CRM.NS}P23i_surrendered_title_through`,
    P24: `${uri.CRM.NS}P24_transferred_title_of`,
    P24i: `${uri.CRM.NS}P24i_changed_ownership_through`,
    P25: `${uri.CRM.NS}P25_moved`,
    P25i: `${uri.CRM.NS}P25i_moved_by`,
    P26: `${uri.CRM.NS}P26_moved_to`,
    P26i: `${uri.CRM.NS}P26i_was_destination_of`,
    P27: `${uri.CRM.NS}P27_moved_from`,
    P27i: `${uri.CRM.NS}P27i_was_origin_of`,
    P28: `${uri.CRM.NS}P28_custody_surrendered_by`,
    P28i: `${uri.CRM.NS}P28i_surrendered_custody_through`,
    P29: `${uri.CRM.NS}P29_custody_received_by`,
    P29i: `${uri.CRM.NS}P29i_received_custody_through`,
    P30: `${uri.CRM.NS}P30_transferred_custody_of`,
    P30i: `${uri.CRM.NS}P30i_custody_transferred_through`,
    P31: `${uri.CRM.NS}P31_has_modified`,
    P31i: `${uri.CRM.NS}P31i_was_modified_by`,
    P32: `${uri.CRM.NS}P32_used_general_technique`,
    P32i: `${uri.CRM.NS}P32i_was_technique_of`,
    P33: `${uri.CRM.NS}P33_used_specific_technique`,
    P33i: `${uri.CRM.NS}P33i_was_used_by`,
    P34: `${uri.CRM.NS}P34_concerned`,
    P34i: `${uri.CRM.NS}P34i_was_assessed_by`,
    P35: `${uri.CRM.NS}P35_has_identified`,
    P35i: `${uri.CRM.NS}P35i_was_identified_by`,
    P37: `${uri.CRM.NS}P37_assigned`,
    P37i: `${uri.CRM.NS}P37i_was_assigned_by`,
    P38: `${uri.CRM.NS}P38_deassigned`,
    P38i: `${uri.CRM.NS}P38i_was_deassigned_by`,
    P39: `${uri.CRM.NS}P39_measured`,
    P39i: `${uri.CRM.NS}P39i_was_measured_by`,
    P40: `${uri.CRM.NS}P40_observed_dimension`,
    P40i: `${uri.CRM.NS}P40i_was_observed_in`,
    P41: `${uri.CRM.NS}P41_classified`,
    P41i: `${uri.CRM.NS}P41i_was_classified_by`,
    P42: `${uri.CRM.NS}P42_assigned`,
    P42i: `${uri.CRM.NS}P42i_was_assigned_by`,
    P43: `${uri.CRM.NS}P43_has_dimension`,
    P43i: `${uri.CRM.NS}P43i_is_dimension_of`,
    P44: `${uri.CRM.NS}P44_has_condition`,
    P44i: `${uri.CRM.NS}P44i_condition_of`,
    P45: `${uri.CRM.NS}P45_consists_of`,
    P45i: `${uri.CRM.NS}P45i_is_incorporated_in`,
    P46: `${uri.CRM.NS}P46_is_composed_of`,
    P46i: `${uri.CRM.NS}P46i_forms_part_of`,
    P48: `${uri.CRM.NS}P48_has_preferred_identifier`,
    P48i: `${uri.CRM.NS}P48i_is_preferred_identifier_of`,
    P49: `${uri.CRM.NS}P49_has_former_or_current_keeper`,
    P49i: `${uri.CRM.NS}P49i_is_former_or_current_keeper_of`,
    P50: `${uri.CRM.NS}P50_has_current_keeper`,
    P50i: `${uri.CRM.NS}P50i_is_current_keeper_of`,
    P51: `${uri.CRM.NS}P51_has_former_or_current_owner`,
    P51i: `${uri.CRM.NS}P51i_is_former_or_current_owner_of`,
    P52: `${uri.CRM.NS}P52_has_current_owner`,
    P52i: `${uri.CRM.NS}P52i_is_current_owner_of`,
    P53: `${uri.CRM.NS}P53_has_former_or_current_location`,
    P53i: `${uri.CRM.NS}P53i_is_former_or_current_location_of`,
    P54: `${uri.CRM.NS}P54_has_current_permanent_location`,
    P54i: `${uri.CRM.NS}P54i_is_current_permanent_location_of`,
    P55: `${uri.CRM.NS}P55_has_current_location`,
    P55i: `${uri.CRM.NS}P55i_currently_holds`,
    P56: `${uri.CRM.NS}P56_bears_feature`,
    P56i: `${uri.CRM.NS}P56i_is_found_on`,
    P57: `${uri.CRM.NS}P57_has_number_of_parts`,
    P58: `${uri.CRM.NS}P58_has_section_definition`,
    P58i: `${uri.CRM.NS}P58i_defines_section`,
    P59: `${uri.CRM.NS}P59_has_section`,
    P59i: `${uri.CRM.NS}P59i_is_located_on_or_within`,
    P62: `${uri.CRM.NS}P62_depicts`,
    P62i: `${uri.CRM.NS}P62i_is_depicted_by`,
    P65: `${uri.CRM.NS}P65_shows_visual_item`,
    P65i: `${uri.CRM.NS}P65i_is_shown_by`,
    P67: `${uri.CRM.NS}P67_refers_to`,
    P67i: `${uri.CRM.NS}P67i_is_referred_to_by`,
    P68: `${uri.CRM.NS}P68_foresees_use_of`,
    P68i: `${uri.CRM.NS}P68i_use_foreseen_by`,
    P69: `${uri.CRM.NS}P69_is_associated_with`,
    P70: `${uri.CRM.NS}P70_documents`,
    P70i: `${uri.CRM.NS}P70i_is_documented_in`,
    P71: `${uri.CRM.NS}P71_lists`,
    P71i: `${uri.CRM.NS}P71i_is_listed_in`,
    P72: `${uri.CRM.NS}P72_has_language`,
    P72i: `${uri.CRM.NS}P72i_is_language_of`,
    P73: `${uri.CRM.NS}P73_has_translation`,
    P73i: `${uri.CRM.NS}P73i_is_translation_of`,
    P74: `${uri.CRM.NS}P74_has_current_or_former_residence`,
    P74i: `${uri.CRM.NS}P74i_is_current_or_former_residence_of`,
    P75: `${uri.CRM.NS}P75_possesses`,
    P75i: `${uri.CRM.NS}P75i_is_possessed_by`,
    P76: `${uri.CRM.NS}P76_has_contact_point`,
    P76i: `${uri.CRM.NS}P76i_provides_access_to`,
    P78: `${uri.CRM.NS}P78_is_identified_by`,
    P78i: `${uri.CRM.NS}P78i_identifies`,
    P79: `${uri.CRM.NS}P79_beginning_is_qualified_by`,
    P80: `${uri.CRM.NS}P80_end_is_qualified_by`,
    P81: `${uri.CRM.NS}P81_ongoing_throughout`,
    P82: `${uri.CRM.NS}P82_at_some_time_within`,
    P83: `${uri.CRM.NS}P83_had_at_least_duration`,
    P83i: `${uri.CRM.NS}P83i_was_minimum_duration_of`,
    P84: `${uri.CRM.NS}P84_had_at_most_duration`,
    P84i: `${uri.CRM.NS}P84i_was_maximum_duration_of`,
    P86: `${uri.CRM.NS}P86_falls_within`,
    P86i: `${uri.CRM.NS}P86i_contains`,
    P87: `${uri.CRM.NS}P87_is_identified_by`,
    P87i: `${uri.CRM.NS}P87i_identifies`,
    P88: `${uri.CRM.NS}P88_consists_of`,
    P88i: `${uri.CRM.NS}P88i_forms_part_of`,
    P89: `${uri.CRM.NS}P89_falls_within`,
    P89i: `${uri.CRM.NS}P89i_contains`,
    P90: `${uri.CRM.NS}P90_has_value`,
    P91: `${uri.CRM.NS}P91_has_unit`,
    P91i: `${uri.CRM.NS}P91i_is_unit_of`,
    P92: `${uri.CRM.NS}P92_brought_into_existence`,
    P92i: `${uri.CRM.NS}P92i_was_brought_into_existence_by`,
    P93: `${uri.CRM.NS}P93_took_out_of_existence`,
    P93i: `${uri.CRM.NS}P93i_was_taken_out_of_existence_by`,
    P94: `${uri.CRM.NS}P94_has_created`,
    P94i: `${uri.CRM.NS}P94i_was_created_by`,
    P95: `${uri.CRM.NS}P95_has_formed`,
    P95i: `${uri.CRM.NS}P95i_was_formed_by`,
    P96: `${uri.CRM.NS}P96_by_mother`,
    P96i: `${uri.CRM.NS}P96i_gave_birth`,
    P97: `${uri.CRM.NS}P97_from_father`,
    P97i: `${uri.CRM.NS}P97i_was_father_for`,
    P98: `${uri.CRM.NS}P98_brought_into_life`,
    P98i: `${uri.CRM.NS}P98i_was_born`,
    P99: `${uri.CRM.NS}P99_dissolved`,
    P99i: `${uri.CRM.NS}P99i_was_dissolved_by`,
    P100: `${uri.CRM.NS}P100_was_death_of`,
    P100i: `${uri.CRM.NS}P100i_died_in`,
    P101: `${uri.CRM.NS}P101_had_as_general_use`,
    P101i: `${uri.CRM.NS}P101i_was_use_of`,
    P102: `${uri.CRM.NS}P102_has_title`,
    P102i: `${uri.CRM.NS}P102i_is_title_of`,
    P103: `${uri.CRM.NS}P103_was_intended_for`,
    P103i: `${uri.CRM.NS}P103i_was_intention_of`,
    P104: `${uri.CRM.NS}P104_is_subject_to`,
    P104i: `${uri.CRM.NS}P104i_applies_to`,
    P105: `${uri.CRM.NS}P105_right_held_by`,
    P105i: `${uri.CRM.NS}P105i_has_right_on`,
    P106: `${uri.CRM.NS}P106_is_composed_of`,
    P106i: `${uri.CRM.NS}P106i_forms_part_of`,
    P107: `${uri.CRM.NS}P107_has_current_or_former_member`,
    P107i: `${uri.CRM.NS}P107i_is_current_or_former_member_of`,
    P108: `${uri.CRM.NS}P108_has_produced`,
    P108i: `${uri.CRM.NS}P108i_was_produced_by`,
    P109: `${uri.CRM.NS}P109_has_current_or_former_curator`,
    P109i: `${uri.CRM.NS}P109i_is_current_or_former_curator_of`,
    P110: `${uri.CRM.NS}P110_augmented`,
    P110i: `${uri.CRM.NS}P110i_was_augmented_by`,
    P111: `${uri.CRM.NS}P111_added`,
    P111i: `${uri.CRM.NS}P111i_was_added_by`,
    P112: `${uri.CRM.NS}P112_diminished`,
    P112i: `${uri.CRM.NS}P112i_was_diminished_by`,
    P113: `${uri.CRM.NS}P113_removed`,
    P113i: `${uri.CRM.NS}P113i_was_removed_by`,
    P114: `${uri.CRM.NS}P114_is_equal_in_time_to`,
    P115: `${uri.CRM.NS}P115_finishes`,
    P115i: `${uri.CRM.NS}P115i_is_finished_by`,
    P116: `${uri.CRM.NS}P116_starts`,
    P116i: `${uri.CRM.NS}P116i_is_started_by`,
    P117: `${uri.CRM.NS}P117_occurs_during`,
    P117i: `${uri.CRM.NS}P117i_includes`,
    P118: `${uri.CRM.NS}P118_overlaps_in_time_with`,
    P118i: `${uri.CRM.NS}P118i_is_overlapped_in_time_by`,
    P119: `${uri.CRM.NS}P119_meets_in_time_with`,
    P119i: `${uri.CRM.NS}P119i_is_met_in_time_by`,
    P120: `${uri.CRM.NS}P120_occurs_before`,
    P120i: `${uri.CRM.NS}P120i_occurs_after`,
    P121: `${uri.CRM.NS}P121_overlaps_with`,
    P122: `${uri.CRM.NS}P122_borders_with`,
    P123: `${uri.CRM.NS}P123_resulted_in`,
    P123i: `${uri.CRM.NS}P123i_resulted_from`,
    P124: `${uri.CRM.NS}P124_transformed`,
    P124i: `${uri.CRM.NS}P124i_was_transformed_by`,
    P125: `${uri.CRM.NS}P125_used_object_of_type`,
    P125i: `${uri.CRM.NS}P125i_was_type_of_object_used_in`,
    P126: `${uri.CRM.NS}P126_employed`,
    P126i: `${uri.CRM.NS}P126i_was_employed_in`,
    P127: `${uri.CRM.NS}P127_has_broader_term`,
    P127i: `${uri.CRM.NS}P127i_has_narrower_term`,
    P128: `${uri.CRM.NS}P128_carries`,
    P128i: `${uri.CRM.NS}P128i_is_carried_by`,
    P129: `${uri.CRM.NS}P129_is_about`,
    P129i: `${uri.CRM.NS}P129i_is_subject_of`,
    P130: `${uri.CRM.NS}P130_shows_features_of`,
    P130i: `${uri.CRM.NS}P130i_features_are_also_found_on`,
    P131: `${uri.CRM.NS}P131_is_identified_by`,
    P131i: `${uri.CRM.NS}P131i_identifies`,
    P132: `${uri.CRM.NS}P132_overlaps_with`,
    P133: `${uri.CRM.NS}P133_is_separated_from`,
    P134: `${uri.CRM.NS}P134_continued`,
    P134i: `${uri.CRM.NS}P134i_was_continued_by`,
    P135: `${uri.CRM.NS}P135_created_type`,
    P135i: `${uri.CRM.NS}P135i_was_created_by`,
    P136: `${uri.CRM.NS}P136_was_based_on`,
    P136i: `${uri.CRM.NS}P136i_supported_type_creation`,
    P137: `${uri.CRM.NS}P137_exemplifies`,
    P137i: `${uri.CRM.NS}P137i_is_exemplified_by`,
    P138: `${uri.CRM.NS}P138_represents`,
    P138i: `${uri.CRM.NS}P138i_has_representation`,
    P139: `${uri.CRM.NS}P139_has_alternative_form`,
    P140: `${uri.CRM.NS}P140_assigned_attribute_to`,
    P140i: `${uri.CRM.NS}P140i_was_attributed_by`,
    P141: `${uri.CRM.NS}P141_assigned`,
    P141i: `${uri.CRM.NS}P141i_was_assigned_by`,
    P142: `${uri.CRM.NS}P142_used_constituent`,
    P142i: `${uri.CRM.NS}P142i_was_used_in`,
    P143: `${uri.CRM.NS}P143_joined`,
    P143i: `${uri.CRM.NS}P143i_was_joined_by`,
    P144: `${uri.CRM.NS}P144_joined_with`,
    P144i: `${uri.CRM.NS}P144i_gained_member_by`,
    P145: `${uri.CRM.NS}P145_separated`,
    P145i: `${uri.CRM.NS}P145i_left_by`,
    P146: `${uri.CRM.NS}P146_separated_from`,
    P146i: `${uri.CRM.NS}P146i_lost_member_by`,
    P147: `${uri.CRM.NS}P147_curated`,
    P147i: `${uri.CRM.NS}P147i_was_curated_by`,
    P148: `${uri.CRM.NS}P148_has_component`,
    P148i: `${uri.CRM.NS}P148i_is_component_of`,
    P149: `${uri.CRM.NS}P149_is_identified_by`,
    P149i: `${uri.CRM.NS}P149i_identifies`
}

/*
uri.FOAF - Friend of a Friend
usage: alert(uri.FOAF.PERSON) | alert(uri.FOAF["PERSON"])
both return "http://xmlns.com/foaf/0.1/Person"
*/
uri.FOAF = { NS: "http://xmlns.com/foaf/0.1/" }
uri.FOAF = {
    NS: uri.FOAF.NS, // else it is overwritten
    // entities / classes
    AGENT: `${uri.FOAF.NS}Agent`,
    DOCUMENT: `${uri.FOAF.NS}Document`,
    GROUP: `${uri.FOAF.NS}Group`,
    IMAGE: `${uri.FOAF.NS}Image`,
    ONLINEACCOUNT: `${uri.FOAF.NS}OnlineAccount`,
    ORGANIZATION: `${uri.FOAF.NS}Organization`,
    PERSON: `${uri.FOAF.NS}Person`,
    PERSONALPROFILEDOCUMENT: `${uri.FOAF.NS}PersonalProfileDocument`,
    PROJECT: `${uri.FOAF.NS}Project`,    
    // properties
    ACCOUNT: `${uri.FOAF.NS}account`,
    ACCOUNTNAME: `${uri.FOAF.NS}accountName`,
    ACCOUNTSERVICEHOMEPAGE: `${uri.FOAF.NS}accountServiceHomepage`,
    AGE: `${uri.FOAF.NS}age`,
    BASEDNEAR: `${uri.FOAF.NS}basedNear`,
    CURRENTPROJECT: `${uri.FOAF.NS}currentProject`,
    DEPICTION: `${uri.FOAF.NS}depiction`,
    DEPICTS: `${uri.FOAF.NS}depicts`,
    FAMILYNAME: `${uri.FOAF.NS}familyName`,
    GIVENNAME: `${uri.FOAF.NS}givenName`,
    HOMEPAGE: `${uri.FOAF.NS}homePage`,
    IMG: `${uri.FOAF.NS}img`,
    INTEREST: `${uri.FOAF.NS}interest`,
    ISPRIMARYTOPICOF: `${uri.FOAF.NS}isPrimaryTopicOf`,
    JABBERID: `${uri.FOAF.NS}jabberID`,
    KNOWS: `${uri.FOAF.NS}knows`,
    LOGO: `${uri.FOAF.NS}logo`,
    MADE: `${uri.FOAF.NS}made`,
    MAKER: `${uri.FOAF.NS}maker`,
    MBOX: `${uri.FOAF.NS}mbox`,
    MBOXSHA1SUM: `${uri.FOAF.NS}mbox_sha1sum`,
    MEMBER: `${uri.FOAF.NS}member`,
    NAME: `${uri.FOAF.NS}name`,
    NICK: `${uri.FOAF.NS}nick`,
    OPENID: `${uri.FOAF.NS}openid`,
    PAGE: `${uri.FOAF.NS}page`,
    PASTPROJECT: `${uri.FOAF.NS}pastProject`,
    PRIMARYTOPIC: `${uri.FOAF.NS}primaryTopic`,
    PUBLICATIONS: `${uri.FOAF.NS}publications`,
    SCHOOLHOMEPAGE: `${uri.FOAF.NS}schoolHomepage`,
    SHA1: `${uri.FOAF.NS}sha1`,
    THUMBNAIL: `${uri.FOAF.NS}thumbnail`,
    TIPJAR: `${uri.FOAF.NS}tipjar`,
    TITLE: `${uri.FOAF.NS}title`,
    TOPIC: `${uri.FOAF.NS}topic`,
    TOPICINTEREST: `${uri.FOAF.NS}topic_interest`,
    WEBLOG: `${uri.FOAF.NS}weblog`,
    WORKINFOHOMEPAGE: `${uri.FOAF.NS}workInfoHomepage`,
    WORKPLACEHOMEPAGE: `${uri.FOAF.NS}workplaceHomepage`
}

/*
uri.SCHEMA - schema.org entities and properties [NOTE: Incomplete]
usage: alert(uri.SCHEMA.PERSON) | alert(uri.SCHEMA["PERSON"])
both return "http://schema.org/Person" 
*/  
uri.SCHEMA = { NS: "http://schema.org/" }
uri.SCHEMA = {
    NS: uri.SCHEMA.NS, // else it is overwritten
    // entities (top level only)
    ACTION: `${uri.SCHEMA.NS}Action`,
    BROADCASTSERVICE: `${uri.SCHEMA.NS}BroadcastService`,
    CREATIVEWORK: `${uri.SCHEMA.NS}CreativeWork`,
    EVENT: `${uri.SCHEMA.NS}Event`,
    INTANGIBLE: `${uri.SCHEMA.NS}Intangible`,
    MEDICALENTITY: `${uri.SCHEMA.NS}MedicalEntity`,
    ORGANIZATION: `${uri.SCHEMA.NS}Organization`,
    PERSON: `${uri.SCHEMA.NS}Person`,
    PLACE: `${uri.SCHEMA.NS}Place`,
    PRODUCT: `${uri.SCHEMA.NS}Product`,
    THING: `${uri.SCHEMA.NS}Thing`,
    // properties (of top level entities only)
    ABOUT: `${uri.SCHEMA.NS}about`,
    ACCESSIBILITYAPI: `${uri.SCHEMA.NS}accessibilityAPI`,
    ACCESSIBILITYCONTROL: `${uri.SCHEMA.NS}accessibilityControl`,
    ACCESSIBILITYFEATURE: `${uri.SCHEMA.NS}accessibilityFeature`,
    ACCESSIBILITYHAZARD: `${uri.SCHEMA.NS}accessibilityHazard`,
    ACCOUNTABLEPERSON: `${uri.SCHEMA.NS}accountablePerson`,
    ACTIONSTATUS: `${uri.SCHEMA.NS}actionStatus`,
    ADDITIONALNAME: `${uri.SCHEMA.NS}additionalName`,
    ADDITIONALTYPE: `${uri.SCHEMA.NS}additionalType`,
    ADDRESS: `${uri.SCHEMA.NS}address`,
    AFFILIATION: `${uri.SCHEMA.NS}affiliation`,
    AGENT: `${uri.SCHEMA.NS}agent`,
    AGGREGATERATING: `${uri.SCHEMA.NS}aggregateRating`,
    ALTERNATIVEHEADLINE: `${uri.SCHEMA.NS}alternativeHeadline`,
    ALTERNATENAME: `${uri.SCHEMA.NS}alternateName`,
    ALUMNIOF: `${uri.SCHEMA.NS}alumniOf`,
    AREA: `${uri.SCHEMA.NS}area`,
    ASSOCIATEDMEDIA: `${uri.SCHEMA.NS}associatedMedia`,
    ATTENDEE: `${uri.SCHEMA.NS}attendee`,
    AUDIENCE: `${uri.SCHEMA.NS}audience`,
    AUDIO: `${uri.SCHEMA.NS}audio`,
    AUTHOR: `${uri.SCHEMA.NS}author`,
    AWARD: `${uri.SCHEMA.NS}award`,
    BIRTHDATE: `${uri.SCHEMA.NS}birthDate`,
    BIRTHPLACE: `${uri.SCHEMA.NS}birthPlace`,
    BRAND: `${uri.SCHEMA.NS}brand`,
    BROADCASTER: `${uri.SCHEMA.NS}broadcaster`,
    CATEGORY: `${uri.SCHEMA.NS}category`,
    CHARACTER: `${uri.SCHEMA.NS}character`,
    CHARACTERATTRIBUTE: `${uri.SCHEMA.NS}characterAttribute`,
    CHILDREN: `${uri.SCHEMA.NS}children`,
    CITATION: `${uri.SCHEMA.NS}citation`,
    CODE: `${uri.SCHEMA.NS}code`,
    COLLEAGUE: `${uri.SCHEMA.NS}colleague`,
    COLLECTION: `${uri.SCHEMA.NS}collection`,
    COLOR: `${uri.SCHEMA.NS}color`,
    COMMENT: `${uri.SCHEMA.NS}comment`,
    COMMENTCOUNT: `${uri.SCHEMA.NS}commentCount`,
    CONTACTPOINT: `${uri.SCHEMA.NS}contactPoint`,
    CONTAINEDIN: `${uri.SCHEMA.NS}containedIn`,
    CONTENTLOCATION: `${uri.SCHEMA.NS}contentLocation`,
    CONTENTRATING: `${uri.SCHEMA.NS}contentRating`,
    CONTRIBUTOR: `${uri.SCHEMA.NS}contributor`,
    COPYRIGHTHOLDER: `${uri.SCHEMA.NS}copyrightHolder`,
    COPYRIGHTYEAR: `${uri.SCHEMA.NS}copyrightYear`,
    CREATOR: `${uri.SCHEMA.NS}creator`,
    DATECREATED: `${uri.SCHEMA.NS}dateCreated`,
    DATEMODIFIED: `${uri.SCHEMA.NS}dateModified`,
    DATEPUBLISHED: `${uri.SCHEMA.NS}datePublished`,
    DEATHDATE: `${uri.SCHEMA.NS}deathDate`,
    DEATHPLACE: `${uri.SCHEMA.NS}deathPlace`,
    DEFAULTVALUE: `${uri.SCHEMA.NS}defaultValue`,
    DEPARTMENT: `${uri.SCHEMA.NS}department`,
    DEPTH: `${uri.SCHEMA.NS}depth`,
    DESCRIPTION: `${uri.SCHEMA.NS}description`,
    DISCUSSIONURL: `${uri.SCHEMA.NS}discussionUrl`,
    DISSOLUTIONDATE: `${uri.SCHEMA.NS}dissolutionDate`,
    DOORTIME: `${uri.SCHEMA.NS}doorTime`,
    DUNS: `${uri.SCHEMA.NS}duns`,
    DURATION: `${uri.SCHEMA.NS}duration`,
    EDITOR: `${uri.SCHEMA.NS}editor`,
    EDUCATIONALALIGNMENT: `${uri.SCHEMA.NS}educationalAlignment`,
    EDUCATIONALUSE: `${uri.SCHEMA.NS}educationalUse`,
    ENCODING: `${uri.SCHEMA.NS}encoding`,
    ENDDATE: `${uri.SCHEMA.NS}endDate`,
    ENDTIME: `${uri.SCHEMA.NS}endTime`,
    EMAIL: `${uri.SCHEMA.NS}email`,
    EMPLOYEE: `${uri.SCHEMA.NS}employee`,
    ERROR: `${uri.SCHEMA.NS}error`,
    EVENTSTATUS: `${uri.SCHEMA.NS}eventStatus`,
    EXAMPLEOFWORK: `${uri.SCHEMA.NS}exampleOfWork`,
    FAMILYNAME: `${uri.SCHEMA.NS}familyName`,
    FAXNUMBER: `${uri.SCHEMA.NS}faxNumber`,
    FIRSTPERFORMANCE: `${uri.SCHEMA.NS}firstPerformance`,
    FOLLOWS: `${uri.SCHEMA.NS}follows`,
    FOUNDER: `${uri.SCHEMA.NS}founder`,
    FOUNDINGDATE: `${uri.SCHEMA.NS}foundingDate`,
    FOUNDINGLOCATION: `${uri.SCHEMA.NS}foundingLocation`,
    GAMEITEM: `${uri.SCHEMA.NS}gameItem`,
    GAMEPLATFORM: `${uri.SCHEMA.NS}gamePlatform`,
    GENRE: `${uri.SCHEMA.NS}genre`,
    GENDER: `${uri.SCHEMA.NS}gender`,
    GEO: `${uri.SCHEMA.NS}geo`,
    GIVENNAME: `${uri.SCHEMA.NS}givenName`,   
    GLOBALLOCATIONNUMBER: `${uri.SCHEMA.NS}globalLocationNumber`,
    GTIN13: `${uri.SCHEMA.NS}gtin13`,
    GTIN14: `${uri.SCHEMA.NS}gtin14`,
    GTIN8: `${uri.SCHEMA.NS}gtin8`,
    GUIDELINE: `${uri.SCHEMA.NS}guideline`,
    HASMAP: `${uri.SCHEMA.NS}hasMap`,
    HASPART: `${uri.SCHEMA.NS}hasPart`,
    HASPOS: `${uri.SCHEMA.NS}hasPOS`,
    HEADLINE: `${uri.SCHEMA.NS}headline`,
    HEIGHT: `${uri.SCHEMA.NS}height`,
    HOMELOCATION: `${uri.SCHEMA.NS}homeLocation`,
    HONORIFICPREFIX: `${uri.SCHEMA.NS}honorificPrefix`,
    HONORIFICSUFFIX: `${uri.SCHEMA.NS}honorificSuffix`,
    IMAGE: `${uri.SCHEMA.NS}image`,
    INLANGUAGE: `${uri.SCHEMA.NS}inLanguage`,
    INSTRUMENT: `${uri.SCHEMA.NS}instrument`,
    INTERACTIONCOUNT: `${uri.SCHEMA.NS}interactionCount`,
    INTERACTIVITYTYPE: `${uri.SCHEMA.NS}interactivityType`,
    ISACCESSORYORSPAREPARTFOR: `${uri.SCHEMA.NS}isAccessoryOrSparePartFor`,
    ISBASEDONURL: `${uri.SCHEMA.NS}isBasedOnUrl`,
    ISCONSUMABLEFOR: `${uri.SCHEMA.NS}isConsumableFor`,
    ISFAMILYFRIENDLY: `${uri.SCHEMA.NS}isFamilyFriendly`,    
    ISICV4: `${uri.SCHEMA.NS}isicV4`,
    ISPARTOF: `${uri.SCHEMA.NS}isPartOf`,
    ISRELATEDTO: `${uri.SCHEMA.NS}isRelatedTo`,
    ISSIMILARTO: `${uri.SCHEMA.NS}isSimilarTo`,
    ITEM: `${uri.SCHEMA.NS}item`,
    ITEMCONDITION: `${uri.SCHEMA.NS}itemCondition`,
    ITEMLISTELEMENT: `${uri.SCHEMA.NS}itemListElement`,
    ITEMREVIEWED: `${uri.SCHEMA.NS}itemReviewed`,
    JOBTITLE: `${uri.SCHEMA.NS}jobTitle`,
    KEYWORDS: `${uri.SCHEMA.NS}keywords`,
    KNOWS: `${uri.SCHEMA.NS}knows`,
    LEARNINGRESOURCETYPE: `${uri.SCHEMA.NS}learningResourceType`,
    LEGALNAME: `${uri.SCHEMA.NS}legalName`,
    LICENSE: `${uri.SCHEMA.NS}license`,
    LOCATION: `${uri.SCHEMA.NS}location`,
    LOGO: `${uri.SCHEMA.NS}logo`,
    MAKESOFFER: `${uri.SCHEMA.NS}makesOffer`,
    MANUFACTURER: `${uri.SCHEMA.NS}manufacturer`,
    MEDICINESYSTEM: `${uri.SCHEMA.NS}medicineSystem`,
    MEMBER: `${uri.SCHEMA.NS}member`,
    MEMBEROF: `${uri.SCHEMA.NS}memberOf`,
    MENTIONS: `${uri.SCHEMA.NS}mentions`,
    MODEL: `${uri.SCHEMA.NS}model`,
    MPN: `${uri.SCHEMA.NS}mpn`,
    NAICS: `${uri.SCHEMA.NS}naics`,
    NAME: `${uri.SCHEMA.NS}name`,
    NATIONALITY: `${uri.SCHEMA.NS}nationality`,
    NETWORTH: `${uri.SCHEMA.NS}netWorth`,
    OBJECT: `${uri.SCHEMA.NS}object`,
    OFFERS: `${uri.SCHEMA.NS}offers`,
    OPENINGHOURSSPECIFICATION: `${uri.SCHEMA.NS}openingHoursSpecification`,
    OPTION: `${uri.SCHEMA.NS}option`,
    ORGANIZER: `${uri.SCHEMA.NS}organizer`,
    OWNS: `${uri.SCHEMA.NS}owns`,
    PARENT: `${uri.SCHEMA.NS}parent`,
    PARENTSERVICE: `${uri.SCHEMA.NS}parentService`,
    PARTICIPANT: `${uri.SCHEMA.NS}participant`,
    PERFORMER: `${uri.SCHEMA.NS}performer`,
    PERFORMERIN: `${uri.SCHEMA.NS}performerIn`,
    PHOTO: `${uri.SCHEMA.NS}photo`,
    POSITION: `${uri.SCHEMA.NS}position`,
    POTENTIALACTION: `${uri.SCHEMA.NS}potentialAction`,
    PREVIOUSSTARTDATE: `${uri.SCHEMA.NS}previousStartDate`,
    PRODUCER: `${uri.SCHEMA.NS}producer`,
    PRODUCES: `${uri.SCHEMA.NS}produces`,
    PRODUCTID: `${uri.SCHEMA.NS}productID`,
    PROGRAMMINGLANGUAGE: `${uri.SCHEMA.NS}programmingLanguage`,
    PROVIDER: `${uri.SCHEMA.NS}provider`,
    PUBLISHEDON: `${uri.SCHEMA.NS}publishedOn`,
    PUBLISHER: `${uri.SCHEMA.NS}publisher`,
    PUBLISHINGPRINCIPLES: `${uri.SCHEMA.NS}publishingPrinciples`,
    PURPOSE: `${uri.SCHEMA.NS}purpose`,
    QUEST: `${uri.SCHEMA.NS}quest`,
    RECOGNIZINGAUTHORITY: `${uri.SCHEMA.NS}recognizingAuthority`,
    RECORDEDAT: `${uri.SCHEMA.NS}recordedAt`,
    RECORDEDIN: `${uri.SCHEMA.NS}recordedIn`,
    RELATEDTO: `${uri.SCHEMA.NS}relatedTo`,
    RELEASEDATE: `${uri.SCHEMA.NS}releaseDate`,
    RELEASEDEVENT: `${uri.SCHEMA.NS}releasedEvent`,
    RELEVANTSPECIALTY: `${uri.SCHEMA.NS}relevantSpecialty`,
    REPLACEE: `${uri.SCHEMA.NS}replacee`,
    REPLACER: `${uri.SCHEMA.NS}replacer`,
    REVIEW: `${uri.SCHEMA.NS}review`,
    RESERVATIONFOR: `${uri.SCHEMA.NS}reservationFor`,
    RESULT: `${uri.SCHEMA.NS}result`,
    SAMEAS: `${uri.SCHEMA.NS}sameAs`,
    SEEKS: `${uri.SCHEMA.NS}seeks`,
    SIBLING: `${uri.SCHEMA.NS}sibling`,
    SKU: `${uri.SCHEMA.NS}sku`,
    SOURCEORGANIZATION: `${uri.SCHEMA.NS}sourceOrganization`,
    SPOUSE: `${uri.SCHEMA.NS}spouse`,
    STARTDATE: `${uri.SCHEMA.NS}startDate`,
    STARTTIME: `${uri.SCHEMA.NS}startTime`,
    STUDY: `${uri.SCHEMA.NS}study`,
    SUBEVENT: `${uri.SCHEMA.NS}subEvent`,
    SUBORGANIZATION: `${uri.SCHEMA.NS}subOrganization`,
    SUPEREVENT: `${uri.SCHEMA.NS}superEvent`,
    TARGET: `${uri.SCHEMA.NS}target`,
    TAXID: `${uri.SCHEMA.NS}taxID`,
    TELEPHONE: `${uri.SCHEMA.NS}telephone`,
    TEXT: `${uri.SCHEMA.NS}text`,
    THUMBNAILURL: `${uri.SCHEMA.NS}thumbnailUrl`,
    TIMEREQUIRED: `${uri.SCHEMA.NS}timeRequired`,
    TRANSLATOR: `${uri.SCHEMA.NS}translator`,
    TYPICALAGERANGE: `${uri.SCHEMA.NS}typicalAgeRange`,
    URL: `${uri.SCHEMA.NS}url`,
    VATID: `${uri.SCHEMA.NS}vatID`,
    VERSION: `${uri.SCHEMA.NS}version`,
    VIDEO: `${uri.SCHEMA.NS}video`,
    WEIGHT: `${uri.SCHEMA.NS}weight`,
    WIDTH: `${uri.SCHEMA.NS}width`,
    WORKEXAMPLE: `${uri.SCHEMA.NS}workExample`,
    WORKLOCATION: `${uri.SCHEMA.NS}workLocation`,
    WORKPERFORMED: `${uri.SCHEMA.NS}workPerformed`,
    WORKSFOR: `${uri.SCHEMA.NS}worksFor`
}
