# =============================================================================
# Project	URI
# Classes	URI::RDF
#		URI::RDFS
#		URI::SKOS
#		URI::SKOSXL
#		URI::CRM42
#		URI::ECRM
#		URI::CRMEH
#		URI::DC
#		URI::DCTERMS
#		URI::OWL
# Summary	Enumerated constants for use within RDF/XML applications	
# Usage		URI::DC::SUBJECT, URI::SKOS::CONCEPT etc.
# -----------------------------------------------------------------------------
# History
# -----------------------------------------------------------------------------
# Ref	Who	DateDetails
# ---	---	-----------
# 001	CFB	24/04/2009	Initially created modules
# 002	CFB	07/08/2009	modules converted to Enumeration classes
# 003	CFB	16/09/2011	classes URI::ECRM and URI::SKOSXL added
# =============================================================================
require "enumeration" # allows each do |key,value| on enumerated constants

module URI
	class RDF < Enumeration
	# namespace
	NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	# entities
	self.add :XMLLITERAL, NS + "XMLLiteral"
	self.add :PROPERTY, NS + "Property"
	self.add :STATEMENT, NS + "Statement"
	self.add :BAG, NS + "Bag"
	self.add :SEQ, NS + "Seq"
	self.add :ALT, NS + "Alt"
	self.add :LIST, NS + "List"
	# properties
	self.add :TYPE, NS + "type"
	self.add :FIRST, NS + "first"
	self.add :REST, NS + "rest"
	self.add :VALUE, NS + "value"
	self.add :SUBJECT, NS + "subject"
	self.add :PREDICATE, NS + "predicate"
	self.add :OBJECT, NS + "object"
	self.add :ID, NS + "ID"
	end # URI::RDF

	class RDFS < Enumeration
	# namespace
	NS = "http://www.w3.org/2000/01/rdf-schema#"
	# entities
	self.add :RESOURCE, NS + "Resource"
	self.add :LITERAL, NS + "Literal"
	self.add :CLASS, NS + "Class"
	self.add :DATATYPE, NS + "Datatype"
	self.add :CONTAINER, NS + "Container"
	self.add :CONTAINERMEMBERSHIPPROPERTY, NS + "ContainerMembershipProperty"
	# properties
	self.add :SUBCLASSOF, NS + "subClassOf"
	self.add :SUBPROPERTYOF, NS + "subPropertyOf"
	self.add :DOMAIN, NS + "domain"
	self.add :RANGE, NS + "range"
	self.add :LABEL, NS + "label"
	self.add :COMMENT, NS + "comment"
	self.add :MEMBER, NS + "member"
	self.add :SEEALSO, NS + "seeAlso"
	self.add :ISDEFINEDBY, NS + "isDefinedBy"
	end # URI::RDFS

	class SKOS < Enumeration
	# namespace
	NS = "http://www.w3.org/2004/02/skos/core#"
	# entities
	self.add :COLLECTABLEPROPERTY, NS + "CollectableProperty"
	self.add :COLLECTION, NS + "Collection"
	self.add :CONCEPT, NS + "Concept"
	self.add :CONCEPTSCHEME, NS + "ConceptScheme"
	self.add :ORDEREDCOLLECTION, NS + "OrderedCollection"
	# properties
	self.add :ALTLABEL, NS + "altLabel"
	self.add :ALTSYMBOL, NS + "altSymbol"
	self.add :BROADER, NS + "broader"
	self.add :CHANGENOTE, NS + "changeNote"
	self.add :DEFINITION, NS + "definition"
	self.add :EDITORIALNOTE, NS + "editorialNote"
	self.add :EXAMPLE, NS + "example"
	self.add :HASTOPCONCEPT, NS + "hasTopConcept"
	self.add :HIDDENLABEL, NS + "hiddenLabel"
	self.add :HISTORYNOTE, NS + "historyNote"
	self.add :INSCHEME, NS + "inScheme"
	self.add :ISPRIMARYSUBJECTOF, NS + "isPrimarySubjectOf"
	self.add :ISSUBJECTOF, NS + "isSubjectOf"
	self.add :MEMBER, NS + "member"
	self.add :MEMBERLIST, NS + "memberList"
	self.add :NARROWER, NS + "narrower"
	self.add :NOTE, NS + "note"
	self.add :PREFLABEL, NS + "prefLabel"
	self.add :PREFSYMBOL, NS + "prefSymbol"
	self.add :PRIMARYSUBJECT, NS + "primarySubject"
	self.add :RELATED, NS + "related"
	self.add :SCOPENOTE, NS + "scopeNote"
	self.add :SEMANTICRELATION, NS + "semanticRelation"
	self.add :SUBJECT, NS + "subject"
	self.add :SUBJECTINDICATOR, NS + "subjectIndicator"
	self.add :SYMBOL, NS + "symbol"
	end # URI::SKOS

	class SKOSXL < Enumeration
	# namespace
	NS = "http://www.w3.org/2008/05/skos-xl#"
	# entities
	self.add :LABEL, NS + "Label"
	# properties
	self.add :PREFLABEL, NS + "prefLabel"
	self.add :ALTLABEL, NS + "altLabel"
	self.add :HIDDENLABEL, NS + "hiddenLabel"
	self.add :LABELRELATION, NS + "labelRelation"
	self.add :LITERALFORM, NS + "literalForm"
	end # URI::SKOSXL

	class CRM42 < Enumeration
	# namespace
	NS = "http://cidoc.ics.forth.gr/rdfs/cidoc_v4.2.rdfs#"
	# entities
	self.add :E1, NS + "E1.CRM_Entity"
  self.add :E2, NS + "E2.Temporal_Entity"
  self.add :E3, NS + "E3.Condition_State"
  self.add :E4, NS + "E4.Period"
  self.add :E5, NS + "E5.Event"
  self.add :E6, NS + "E6.Destruction"
  self.add :E7, NS + "E7.Activity"
  self.add :E8, NS + "E8.Acquisition"
  self.add :E9, NS + "E9.Move"
  self.add :E10, NS + "E10.Transfer_of_Custody"
  self.add :E11, NS + "E11.Modification"
  self.add :E12, NS + "E12.Production"
  self.add :E13, NS + "E13.Attribute_Assignment"
  self.add :E14, NS + "E14.Condition_Assessment"
  self.add :E15, NS + "E15.Identifier_Assignment"
  self.add :E16, NS + "E16.Measurement"
  self.add :E17, NS + "E17.Type_Assignment"
  self.add :E18, NS + "E18.Physical_Thing"
  self.add :E19, NS + "E19.Physical_Object"
  self.add :E20, NS + "E20.Biological_Object"
	self.add :E21, NS + "E21.Person"
  self.add :E22, NS + "E22.Man-Made_Object"
  self.add :E24, NS + "E24.Physical_Man-Made_Thing"
  self.add :E25, NS + "E25.Man-Made_Feature"
  self.add :E26, NS + "E26.Physical_Feature"
  self.add :E27, NS + "E27.Site"
  self.add :E28, NS + "E28.Conceptual_Object"
  self.add :E29, NS + "E29.Design_or_Procedure"
  self.add :E30, NS + "E30.Right"
  self.add :E31, NS + "E31.Document"
  self.add :E32, NS + "E32.Authority_Document"
  self.add :E33, NS + "E33.Linguistic_Object"
  self.add :E34, NS + "E34.Inscription"
  self.add :E35, NS + "E35.Title"
  self.add :E36, NS + "E36.Visual_Item"
  self.add :E37, NS + "E37.Mark"
  self.add :E38, NS + "E38.Image"
  self.add :E39, NS + "E39.Actor"
  self.add :E40, NS + "E40.Legal_Body"
  self.add :E41, NS + "E41.Appellation"
  self.add :E42, NS + "E42.Object_Identifier"
  self.add :E44, NS + "E44.Place_Appellation"
  self.add :E45, NS + "E45.Address"
  self.add :E46, NS + "E46.Section_Definition"
  self.add :E47, NS + "E47.Spatial_Coordinates"
  self.add :E48, NS + "E48.Place_Name"
  self.add :E49, NS + "E49.Time_Appellation"
  self.add :E50, NS + "E50.Date"
  self.add :E51, NS + "E51.Contact_Point"
  self.add :E52, NS + "E52.Time-Span"
  self.add :E53, NS + "E53.Place"
  self.add :E54, NS + "E54.Dimension"
  self.add :E55, NS + "E55.Type"
  self.add :E56, NS + "E56.Language"
  self.add :E57, NS + "E57.Material"
  self.add :E58, NS + "E58.Measurement_Unit"
  self.add :E59, NS + "E59.Primitive_Value"
  self.add :E60, NS + "E60.Number"
  self.add :E61, NS + "E61.Time_Primitive"
  self.add :E62, NS + "E62.String"
  self.add :E63, NS + "E63.Beginning_of_Existence"
  self.add :E64, NS + "E64.End_of_Existence"
  self.add :E65, NS + "E65.Creation"
  self.add :E66, NS + "E66.Formation"
  self.add :E67, NS + "E67.Birth"
  self.add :E68, NS + "E68.Dissolution"
  self.add :E69, NS + "E69.Death"
  self.add :E70, NS + "E70.Thing"
  self.add :E71, NS + "E71.Man-Made_Thing"
  self.add :E72, NS + "E72.Legal_Object"
  self.add :E73, NS + "E73.Information_Object"
  self.add :E74, NS + "E74.Group"
  self.add :E75, NS + "E75.Conceptual_Object_Appellation"
  self.add :E77, NS + "E77.Persistent_Item"
  self.add :E78, NS + "E78.Collection"
  self.add :E79, NS + "E79.Part_Addition"
  self.add :E80, NS + "E80.Part_Removal"
  self.add :E81, NS + "E81.Transformation"
  self.add :E82, NS + "E82.Actor_Appellation"
  self.add :E83, NS + "E83.Type_Creation"
  self.add :E84, NS + "E84.Information_Carrier"
	#properties
	self.add :P1F, NS + "P1F.is_identified_by"
  self.add :P1B, NS + "P1B.identifies"
  self.add :P2F, NS + "P2F.has_type"
  self.add :P2B, NS + "P2B.is_type_of"
  self.add :P3F, NS + "P3F.has_note"
  self.add :P4F, NS + "P4F.has_time-span"
  self.add :P4B, NS + "P4B.is_time-span_of"
  self.add :P5F, NS + "P5F.consists_of"
  self.add :P5B, NS + "P5B.forms_part_of"
  self.add :P7F, NS + "P7F.took_place_at"
  self.add :P7B, NS + "P7B.witnessed"
  self.add :P8F, NS + "P8F.took_place_on_or_within"
  self.add :P8B, NS + "P8B.witnessed"
  self.add :P9F, NS + "P9F.consists_of"
  self.add :P9B, NS + "P9B.forms_part_of"
  self.add :P10F, NS + "P10F.falls_within"
  self.add :P10B, NS + "P10B.contains"
  self.add :P11F, NS + "P11F.had_participant"
  self.add :P11B, NS + "P11B.participated_in"
  self.add :P12F, NS + "P12F.occurred_in_the_presence_of"
  self.add :P12B, NS + "P12B.was_present_at"
  self.add :P13F, NS + "P13F.destroyed"
  self.add :P13B, NS + "P13B.was_destroyed_by"
  self.add :P14F, NS + "P14F.carried_out_by"
  self.add :P14B, NS + "P14B.performed"
  self.add :P15F, NS + "P15F.was_influenced_by"
  self.add :P15B, NS + "P15B.influenced"
  self.add :P16F, NS + "P16F.used_specific_object"
  self.add :P16B, NS + "P16B.was_used_for"
  self.add :P17F, NS + "P17F.was_motivated_by"
  self.add :P17B, NS + "P17B.motivated"
  self.add :P19F, NS + "P19F.was_intended_use_of"
  self.add :P19B, NS + "P19B.was_made_for"
  self.add :P20F, NS + "P20F.had_specific_purpose"
  self.add :P20B, NS + "P20B.was_purpose_of"
  self.add :P21F, NS + "P21F.had_general_purpose"
  self.add :P21B, NS + "P21B.was_purpose_of"
  self.add :P22F, NS + "P22F.transferred_title_to"
  self.add :P22B, NS + "P22B.acquired_title_through"
  self.add :P23F, NS + "P23F.transferred_title_from"
  self.add :P23B, NS + "P23B.surrendered_title_through"
  self.add :P24F, NS + "P24F.transferred_title_of"
  self.add :P24B, NS + "P24B.changed_ownership_through"
  self.add :P25F, NS + "P25F.moved"
  self.add :P25B, NS + "P25B.moved_by"
  self.add :P26F, NS + "P26F.moved_to"
  self.add :P26B, NS + "P26B.was_destination_of"
  self.add :P27F, NS + "P27F.moved_from"
  self.add :P27B, NS + "P27B.was_origin_of"
  self.add :P28F, NS + "P28F.custody_surrendered_by"
  self.add :P28B, NS + "P28B.surrendered_custody_through"
  self.add :P29F, NS + "P29F.custody_received_by"
  self.add :P29B, NS + "P29B.received_custody_through"
  self.add :P30F, NS + "P30F.transferred_custody_of"
  self.add :P30B, NS + "P30B.custody_transferred_through"
  self.add :P31F, NS + "P31F.has_modified"
  self.add :P31B, NS + "P31B.was_modified_by"
  self.add :P32F, NS + "P32F.used_general_technique"
  self.add :P32B, NS + "P32B.was_technique_of"
  self.add :P33F, NS + "P33F.used_specific_technique"
  self.add :P33B, NS + "P33B.was_used_by"
  self.add :P34F, NS + "P34F.concerned"
  self.add :P34B, NS + "P34B.was_assessed_by"
  self.add :P35F, NS + "P35F.has_identified"
  self.add :P35B, NS + "P35B.identified_by"
  self.add :P36F, NS + "P36F.registered"
  self.add :P36B, NS + "P36B.was_registered_by"
  self.add :P37F, NS + "P37F.assigned"
  self.add :P37B, NS + "P37B.was_assigned_by"
  self.add :P38F, NS + "P38F.deassigned"
  self.add :P38B, NS + "P38B.was_deassigned_by"
  self.add :P39F, NS + "P39F.measured"
  self.add :P39B, NS + "P39B.was_measured_by"
  self.add :P40F, NS + "P40F.observed_dimension"
  self.add :P40B, NS + "P40B.was_observed_in"
  self.add :P41F, NS + "P41F.classified"
  self.add :P41B, NS + "P41B.was_classified_by"
  self.add :P42F, NS + "P42F.assigned"
  self.add :P42B, NS + "P42B.was_assigned_by"
  self.add :P43F, NS + "P43F.has_dimension"
  self.add :P43B, NS + "P43B.is_dimension_of"
  self.add :P44F, NS + "P44F.has_condition"
  self.add :P44B, NS + "P44B.is_condition_of"
  self.add :P45F, NS + "P45F.consists_of"
  self.add :P45B, NS + "P45B.is_incorporated_in"
  self.add :P46F, NS + "P46F.is_composed_of"
  self.add :P46B, NS + "P46B.forms_part_of"
  self.add :P47F, NS + "P47F.is_identified_by"
  self.add :P47B, NS + "P47B.identifies"
  self.add :P48F, NS + "P48F.has_preferred_identifier"
  self.add :P48B, NS + "P48B.is_preferred_identifier_of"
  self.add :P49F, NS + "P49F.has_former_or_current_keeper"
  self.add :P49B, NS + "P49B.is_former_or_current_keeper_of"
  self.add :P50F, NS + "P50F.has_current_keeper"
  self.add :P50B, NS + "P50B.is_current_keeper_of"
  self.add :P51F, NS + "P51F.has_former_or_current_owner"
  self.add :P51B, NS + "P51B.is_former_or_current_owner_of"
  self.add :P52F, NS + "P52F.has_current_owner"
  self.add :P52B, NS + "P52B.is_current_owner_of"
  self.add :P53F, NS + "P53F.has_former_or_current_location"
  self.add :P53B, NS + "P53B.is_former_or_current_location_of"
  self.add :P54F, NS + "P54F.has_current_permanent_location"
  self.add :P54B, NS + "P54B.is_current_permanent_location_of"
  self.add :P55F, NS + "P55F.has_current_location"
  self.add :P55B, NS + "P55B.currently_holds"
  self.add :P56F, NS + "P56F.bears_feature"
  self.add :P56B, NS + "P56B.is_found_on"
  self.add :P57F, NS + "P57F.has_number_of_parts"
  self.add :P58F, NS + "P58F.has_section_definition"
  self.add :P58B, NS + "P58B.defines_section"
  self.add :P59F, NS + "P59F.has_section"
  self.add :P59B, NS + "P59B.is_located_on_or_within"
  self.add :P62F, NS + "P62F.depicts"
  self.add :P62B, NS + "P62B.is_depicted_by"
  self.add :P65F, NS + "P65F.shows_visual_item"
  self.add :P65B, NS + "P65B.is_shown_by"
  self.add :P67F, NS + "P67F.refers_to"
  self.add :P67B, NS + "P67B.is_referred_to_by"
  self.add :P68F, NS + "P68F.usually_employs"
  self.add :P68B, NS + "P68B.is_usually_employed_by"
  self.add :P69F, NS + "P69F.is_associated_with"
  self.add :P70F, NS + "P70F.documents"
  self.add :P70B, NS + "P70B.is_documented_in"
  self.add :P71F, NS + "P71F.lists"
  self.add :P71B, NS + "P71B.is_listed_in"
  self.add :P72F, NS + "P72F.has_language"
  self.add :P72B, NS + "P72B.is_language_of"
  self.add :P73F, NS + "P73F.has_translation"
  self.add :P73B, NS + "P73B.is_translation_of"
  self.add :P74F, NS + "P74F.has_current_or_former_residence"
  self.add :P74B, NS + "P74B.is_current_or_former_residence_of"
  self.add :P75F, NS + "P75F.possesses"
  self.add :P75B, NS + "P75B.is_possessed_by"
  self.add :P76F, NS + "P76F.has_contact_point"
  self.add :P76B, NS + "P76B.provides_access_to"
  self.add :P78F, NS + "P78F.is_identified_by"
  self.add :P78B, NS + "P78B.identifies"
  self.add :P79F, NS + "P79F.beginning_is_qualified_by"
  self.add :P80F, NS + "P80F.end_is_qualified_by"
  self.add :P81F, NS + "P81F.ongoing_throughout"
  self.add :P82F, NS + "P82F.at_some_time_within"
  self.add :P83F, NS + "P83F.had_at_least_duration"
  self.add :P83B, NS + "P83B.was_minimum_duration_of"
  self.add :P84F, NS + "P84F.had_at_most_duration"
  self.add :P84B, NS + "P84B.was_maximum_duration_of"
  self.add :P86F, NS + "P86F.falls_within"
  self.add :P86B, NS + "P86B.contains"
  self.add :P87F, NS + "P87F.is_identified_by"
  self.add :P87B, NS + "P87B.identifies"
  self.add :P88F, NS + "P88F.consists_of"
  self.add :P88B, NS + "P88B.forms_part_of"
  self.add :P89F, NS + "P89F.falls_within"
  self.add :P89B, NS + "P89B.contains"
  self.add :P90F, NS + "P90F.has_value"
  self.add :P91F, NS + "P91F.has_unit"
  self.add :P91B, NS + "P91B.is_unit_of"
  self.add :P92F, NS + "P92F.brought_into_existence"
  self.add :P92B, NS + "P92B.was_brought_into_existence_by"
  self.add :P93F, NS + "P93F.took_out_of_existence"
  self.add :P93B, NS + "P93B.was_taken_out_of_existence_by"
  self.add :P94F, NS + "P94F.has_created"
  self.add :P94B, NS + "P94B.was_created_by"
  self.add :P95F, NS + "P95F.has_formed"
  self.add :P95B, NS + "P95B.was_formed_by"
  self.add :P96F, NS + "P96F.by_mother"
  self.add :P96B, NS + "P96B.gave_birth"
  self.add :P97F, NS + "P97F.from_father"
  self.add :P97B, NS + "P97B.was_father_for"
  self.add :P98F, NS + "P98F.brought_into_life"
  self.add :P98B, NS + "P98B.was_born"
  self.add :P99F, NS + "P99F.dissolved"
  self.add :P99B, NS + "P99B.was_dissolved_by"
  self.add :P100F, NS + "P100F.was_death_of"
  self.add :P100B, NS + "P100B.died_in"
  self.add :P101F, NS + "P101F.had_as_general_use"
  self.add :P101B, NS + "P101B.was_use_of"
  self.add :P102F, NS + "P102F.has_title"
  self.add :P102B, NS + "P102B.is_title_of"
  self.add :P103F, NS + "P103F.was_intended_for"
  self.add :P103B, NS + "P103B.was_intention_of"
  self.add :P104F, NS + "P104F.is_subject_to"
  self.add :P104B, NS + "P104B.applies_to"
  self.add :P105F, NS + "P105F.right_held_by"
  self.add :P105B, NS + "P105B.has_right_on"
  self.add :P106F, NS + "P106F.is_composed_of"
  self.add :P106B, NS + "P106B.forms_part_of"
  self.add :P107F, NS + "P107F.has_current_or_former_member"
  self.add :P107B, NS + "P107B.is_current_or_former_member_of"
  self.add :P108F, NS + "P108F.has_produced"
  self.add :P108B, NS + "P108B.was_produced_by"
  self.add :P109F, NS + "P109F.has_current_or_former_curator"
  self.add :P109B, NS + "P109B.is_current_or_former_curator_of"
  self.add :P110F, NS + "P110F.augmented"
  self.add :P110B, NS + "P110B.was_augmented_by"
  self.add :P111F, NS + "P111F.added"
  self.add :P111B, NS + "P111B.was_added_by"
  self.add :P112F, NS + "P112F.diminished"
  self.add :P112B, NS + "P112B.was_diminished_by"
  self.add :P113F, NS + "P113F.removed"
  self.add :P113B, NS + "P113B.was_removed_by"
  self.add :P114F, NS + "P114F.is_equal_in_time_to"
  self.add :P115F, NS + "P115F.finishes"
  self.add :P115B, NS + "P115B.is_finished_by"
  self.add :P116F, NS + "P116F.starts"
  self.add :P116B, NS + "P116B.is_started_by"
  self.add :P117F, NS + "P117F.occurs_during"
  self.add :P117B, NS + "P117B.includes"
  self.add :P118F, NS + "P118F.overlaps_in_time_with"
  self.add :P118B, NS + "P118B.is_overlapped_in_time_by"
  self.add :P119F, NS + "P119F.meets_in_time_with"
  self.add :P119B, NS + "P119B.is_met_in_time_by"
  self.add :P120F, NS + "P120F.occurs_before"
  self.add :P120B, NS + "P120B.occurs_after"
  self.add :P121F, NS + "P121F.overlaps_with"
  self.add :P122F, NS + "P122F.borders_with"
  self.add :P123F, NS + "P123F.resulted_in"
  self.add :P123B, NS + "P123B.resulted_from"
  self.add :P124F, NS + "P124F.transformed"
  self.add :P124B, NS + "P124B.was_transformed_by"
  self.add :P125F, NS + "P125F.used_object_of_type"
  self.add :P125B, NS + "P125B.was_type_of_object_used_in"
  self.add :P126F, NS + "P126F.employed"
  self.add :P126B, NS + "P126B.was_employed_in"
  self.add :P127F, NS + "P127F.has_broader_term"
  self.add :P127B, NS + "P127B.has_narrower_term"
  self.add :P128F, NS + "P128F.carries"
  self.add :P128B, NS + "P128B.is_carried_by"
  self.add :P129F, NS + "P129F.is_about"
  self.add :P129B, NS + "P129B.is_subject_of"
  self.add :P130F, NS + "P130F.shows_features_of"
  self.add :P130B, NS + "P130B.features_are_also_found_on"
  self.add :P131F, NS + "P131F.is_identified_by"
  self.add :P131B, NS + "P131B.identifies"
  self.add :P132F, NS + "P132F.overlaps_with"
  self.add :P133F, NS + "P133F.is_separated_from"
  self.add :P134F, NS + "P134F.continued"
  self.add :P134B, NS + "P134B.was_continued_by"
  self.add :P135F, NS + "P135F.created_type"
  self.add :P135B, NS + "P135B.was_created_by"
  self.add :P136F, NS + "P136F.was_based_on"
  self.add :P136B, NS + "P136B.supported_type_creation"
  self.add :P137F, NS + "P137F.is_exemplified_by"
  self.add :P137B, NS + "P137B.exemplifies"
  self.add :P138F, NS + "P138F.represents"
  self.add :P138B, NS + "P138B.has_representation"
  self.add :P139F, NS + "P139F.has_alternative_form"
  self.add :P140F, NS + "P140F.assigned_attribute_to"
  self.add :P140B, NS + "P140B.was_attributed_by"
  self.add :P141F, NS + "P141F.assigned"
  self.add :P141B, NS + "P141B.was_assigned_by"
	end	# URI::CRM42


	class ECRM < Enumeration
	# namespace
	NS = "http://erlangen-crm.org/110404/"
	# entities
	self.add :E1, NS + "E1_CRM_Entity"
	self.add :E2, NS + "E2_Temporal_Entity"
	self.add :E3, NS + "E3_Condition_State"
	self.add :E4, NS + "E4_Period"
	self.add :E5, NS + "E5_Event"
	self.add :E6, NS + "E6_Destruction"
	self.add :E7, NS + "E7_Activity"
	self.add :E8, NS + "E8_Acquisition"
	self.add :E9, NS + "E9_Move"
	self.add :E10, NS + "E10_Transfer_of_Custody"
	self.add :E11, NS + "E11_Modification"
	self.add :E12, NS + "E12_Production"
	self.add :E13, NS + "E13_Attribute_Assignment"
	self.add :E14, NS + "E14_Condition_Assessment"
	self.add :E15, NS + "E15_Identifier_Assignment"
	self.add :E16, NS + "E16_Measurement"
	self.add :E17, NS + "E17_Type_Assignment"
	self.add :E18, NS + "E18_Physical_Thing"
	self.add :E19, NS + "E19_Physical_Object"
	self.add :E20, NS + "E20_Biological_Object"
	self.add :E21, NS + "E21_Person"
	self.add :E22, NS + "E22_Man-Made_Object"
	self.add :E24, NS + "E24_Physical_Man-Made_Thing"
	self.add :E25, NS + "E25_Man-Made_Feature"
	self.add :E26, NS + "E26_Physical_Feature"
	self.add :E27, NS + "E27_Site"
	self.add :E28, NS + "E28_Conceptual_Object"
	self.add :E29, NS + "E29_Design_or_Procedure"
	self.add :E30, NS + "E30_Right"
	self.add :E31, NS + "E31_Document"
	self.add :E32, NS + "E32_Authority_Document"
	self.add :E33, NS + "E33_Linguistic_Object"
	self.add :E34, NS + "E34_Inscription"
	self.add :E35, NS + "E35_Title"
	self.add :E36, NS + "E36_Visual_Item"
	self.add :E37, NS + "E37_Mark"
	self.add :E38, NS + "E38_Image"
	self.add :E39, NS + "E39_Actor"
	self.add :E40, NS + "E40_Legal_Body"
	self.add :E41, NS + "E41_Appellation"
	self.add :E42, NS + "E42_Identifier"
	self.add :E44, NS + "E44_Place_Appellation"
	self.add :E45, NS + "E45_Address"
	self.add :E46, NS + "E46_Section_Definition"
	self.add :E47, NS + "E47_Spatial_Coordinates"
	self.add :E48, NS + "E48_Place_Name"
	self.add :E49, NS + "E49_Time_Appellation"
	self.add :E50, NS + "E50_Date"
	self.add :E51, NS + "E51_Contact_Point"
	self.add :E52, NS + "E52_Time-Span"
	self.add :E53, NS + "E53_Place"
	self.add :E54, NS + "E54_Dimension"
	self.add :E55, NS + "E55_Type"
	self.add :E56, NS + "E56_Language"
	self.add :E57, NS + "E57_Material"
	self.add :E58, NS + "E58_Measurement_Unit"
	self.add :E59, NS + "E59_Primitive_Value"
	self.add :E60, NS + "E60_Number"
	self.add :E61, NS + "E61_Time_Primitive"
	self.add :E62, NS + "E62_String"
	self.add :E63, NS + "E63_Beginning_of_Existence"
	self.add :E64, NS + "E64_End_of_Existence"
	self.add :E65, NS + "E65_Creation"
	self.add :E66, NS + "E66_Formation"
	self.add :E67, NS + "E67_Birth"
	self.add :E68, NS + "E68_Dissolution"
	self.add :E69, NS + "E69_Death"
	self.add :E70, NS + "E70_Thing"
	self.add :E71, NS + "E71_Man-Made_Thing"
	self.add :E72, NS + "E72_Legal_Object"
	self.add :E73, NS + "E73_Information_Object"
	self.add :E74, NS + "E74_Group"
	self.add :E75, NS + "E75_Conceptual_Object_Appellation"
	self.add :E77, NS + "E77_Persistent_Item"
	self.add :E78, NS + "E78_Collection"
	self.add :E79, NS + "E79_Part_Addition"
	self.add :E80, NS + "E80_Part_Removal"
	self.add :E81, NS + "E81_Transformation"
	self.add :E82, NS + "E82_Actor_Appellation"
	self.add :E83, NS + "E83_Type_Creation"
	self.add :E84, NS + "E84_Information_Carrier"
	self.add :E85, NS + "E85_Joining"
	self.add :E86, NS + "E86_Leaving"
	self.add :E87, NS + "E87_Curation_Activity"
	self.add :E89, NS + "E89_Propositional_Object"
	self.add :E90, NS + "E90_Symbolic_Object"
	#properties
	self.add :P1, NS + "P1_is_identified_by"
	self.add :P1i, NS + "P1i_identifies"
	self.add :P2, NS + "P2_has_type"
	self.add :P2i, NS + "P2i_is_type_of"
	self.add :P3, NS + "P3_has_note"
	self.add :P4, NS + "P4_has_time-span"
	self.add :P4i, NS + "P4i_is_time-span_of"
	self.add :P5, NS + "P5_consists_of"
	self.add :P5i, NS + "P5i_forms_part_of"
	self.add :P7, NS + "P7_took_place_at"
	self.add :P7i, NS + "P7i_witnessed"
	self.add :P8, NS + "P8_took_place_on_or_within"
	self.add :P8i, NS + "P8i_witnessed"
	self.add :P9, NS + "P9_consists_of"
	self.add :P9i, NS + "P9i_forms_part_of"
	self.add :P10, NS + "P10_falls_within"
	self.add :P10i, NS + "P10i_contains"
	self.add :P11, NS + "P11_had_participant"
	self.add :P11i, NS + "P11i_participated_in"
	self.add :P12, NS + "P12_occurred_in_the_presence_of"
	self.add :P12i, NS + "P12i_was_present_at"
	self.add :P13, NS + "P13_destroyed"
	self.add :P13i, NS + "P13i_was_destroyed_by"
	self.add :P14, NS + "P14_carried_out_by"
	self.add :P14i, NS + "P14i_performed"
	self.add :P15, NS + "P15_was_influenced_by"
	self.add :P15i, NS + "P15i_influenced"
	self.add :P16, NS + "P16_used_specific_object"
	self.add :P16i, NS + "P16i_was_used_for"
	self.add :P17, NS + "P17_was_motivated_by"
	self.add :P17i, NS + "P17i_motivated"
	self.add :P19, NS + "P19_was_intended_use_of"
	self.add :P19i, NS + "P19i_was_made_for"
	self.add :P20, NS + "P20_had_specific_purpose"
	self.add :P20i, NS + "P20i_was_purpose_of"
	self.add :P21, NS + "P21_had_general_purpose"
	self.add :P21i, NS + "P21i_was_purpose_of"
	self.add :P22, NS + "P22_transferred_title_to"
	self.add :P22i, NS + "P22i_acquired_title_through"
	self.add :P23, NS + "P23_transferred_title_from"
	self.add :P23i, NS + "P23i_surrendered_title_through"
	self.add :P24, NS + "P24_transferred_title_of"
	self.add :P24i, NS + "P24i_changed_ownership_through"
	self.add :P25, NS + "P25_moved"
	self.add :P25i, NS + "P25i_moved_by"
	self.add :P26, NS + "P26_moved_to"
	self.add :P26i, NS + "P26i_was_destination_of"
	self.add :P27, NS + "P27_moved_from"
	self.add :P27i, NS + "P27i_was_origin_of"
	self.add :P28, NS + "P28_custody_surrendered_by"
	self.add :P28i, NS + "P28i_surrendered_custody_through"
	self.add :P29, NS + "P29_custody_received_by"
	self.add :P29i, NS + "P29i_received_custody_through"
	self.add :P30, NS + "P30_transferred_custody_of"
	self.add :P30i, NS + "P30i_custody_transferred_through"
	self.add :P31, NS + "P31_has_modified"
	self.add :P31i, NS + "P31i_was_modified_by"
	self.add :P32, NS + "P32_used_general_technique"
	self.add :P32i, NS + "P32i_was_technique_of"
	self.add :P33, NS + "P33_used_specific_technique"
	self.add :P33i, NS + "P33i_was_used_by"
	self.add :P34, NS + "P34_concerned"
	self.add :P34i, NS + "P34i_was_assessed_by"
	self.add :P35, NS + "P35_has_identified"
	self.add :P35i, NS + "P35i_was_identified_by"
	self.add :P37, NS + "P37_assigned"
	self.add :P37i, NS + "P37i_was_assigned_by"
	self.add :P38, NS + "P38_deassigned"
	self.add :P38i, NS + "P38i_was_deassigned_by"
	self.add :P39, NS + "P39_measured"
	self.add :P39i, NS + "P39i_was_measured_by"
	self.add :P40, NS + "P40_observed_dimension"
	self.add :P40i, NS + "P40i_was_observed_in"
	self.add :P41, NS + "P41_classified"
	self.add :P41i, NS + "P41i_was_classified_by"
	self.add :P42, NS + "P42_assigned"
	self.add :P42i, NS + "P42i_was_assigned_by"
	self.add :P43, NS + "P43_has_dimension"
	self.add :P43i, NS + "P43i_is_dimension_of"
	self.add :P44, NS + "P44_has_condition"
	self.add :P44i, NS + "P44i_is_condition_of"
	self.add :P45, NS + "P45_consists_of"
	self.add :P45i, NS + "P45i_is_incorporated_in"
	self.add :P46, NS + "P46_is_composed_of"
	self.add :P46i, NS + "P46i_forms_part_of"
	self.add :P48, NS + "P48_has_preferred_identifier"
	self.add :P48i, NS + "P48i_is_preferred_identifier_of"
	self.add :P49, NS + "P49_has_former_or_current_keeper"
	self.add :P49i, NS + "P49i_is_former_or_current_keeper_of"
	self.add :P50, NS + "P50_has_current_keeper"
	self.add :P50i, NS + "P50i_is_current_keeper_of"
	self.add :P51, NS + "P51_has_former_or_current_owner"
	self.add :P51i, NS + "P51i_is_former_or_current_owner_of"
	self.add :P52, NS + "P52_has_current_owner"
	self.add :P52i, NS + "P52i_is_current_owner_of"
	self.add :P53, NS + "P53_has_former_or_current_location"
	self.add :P53i, NS + "P53i_is_former_or_current_location_of"
	self.add :P54, NS + "P54_has_current_permanent_location"
	self.add :P54i, NS + "P54i_is_current_permanent_location_of"
	self.add :P55, NS + "P55_has_current_location"
	self.add :P55i, NS + "P55i_currently_holds"
	self.add :P56, NS + "P56_bears_feature"
	self.add :P56i, NS + "P56i_is_found_on"
	self.add :P57, NS + "P57_has_number_of_parts"
	self.add :P58, NS + "P58_has_section_definition"
	self.add :P58i, NS + "P58i_defines_section"
	self.add :P59, NS + "P59_has_section"
	self.add :P59i, NS + "P59i_is_located_on_or_within"
	self.add :P62, NS + "P62_depicts"
	self.add :P62i, NS + "P62i_is_depicted_by"
	self.add :P65, NS + "P65_shows_visual_item"
	self.add :P65i, NS + "P65i_is_shown_by"
	self.add :P67, NS + "P67_refers_to"
	self.add :P67i, NS + "P67i_is_referred_to_by"
	self.add :P68, NS + "P68_foresees_use_of"
	self.add :P68i, NS + "P68i_use_foreseen_by"
	self.add :P69, NS + "P69_is_associated_with"
	self.add :P70, NS + "P70_documents"
	self.add :P70i, NS + "P70i_is_documented_in"
	self.add :P71, NS + "P71_lists"
	self.add :P71i, NS + "P71i_is_listed_in"
	self.add :P72, NS + "P72_has_language"
	self.add :P72i, NS + "P72i_is_language_of"
	self.add :P73, NS + "P73_has_translation"
	self.add :P73i, NS + "P73i_is_translation_of"
	self.add :P74, NS + "P74_has_current_or_former_residence"
	self.add :P74i, NS + "P74i_is_current_or_former_residence_of"
	self.add :P75, NS + "P75_possesses"
	self.add :P75i, NS + "P75i_is_possessed_by"
	self.add :P76, NS + "P76_has_contact_point"
	self.add :P76i, NS + "P76i_provides_access_to"
	self.add :P78, NS + "P78_is_identified_by"
	self.add :P78i, NS + "P78i_identifies"
	self.add :P79, NS + "P79_beginning_is_qualified_by"
	self.add :P80, NS + "P80_end_is_qualified_by"
	self.add :P81, NS + "P81_ongoing_throughout"
	self.add :P82, NS + "P82_at_some_time_within"
	self.add :P83, NS + "P83_had_at_least_duration"
	self.add :P83i, NS + "P83i_was_minimum_duration_of"
	self.add :P84, NS + "P84_had_at_most_duration"
	self.add :P84i, NS + "P84i_was_maximum_duration_of"
	self.add :P86, NS + "P86_falls_within"
	self.add :P86i, NS + "P86i_contains"
	self.add :P87, NS + "P87_is_identified_by"
	self.add :P87i, NS + "P87i_identifies"
	self.add :P88, NS + "P88_consists_of"
	self.add :P88i, NS + "P88i_forms_part_of"
	self.add :P89, NS + "P89_falls_within"
	self.add :P89i, NS + "P89i_contains"
	self.add :P90, NS + "P90_has_value"
	self.add :P91, NS + "P91_has_unit"
	self.add :P91i, NS + "P91i_is_unit_of"
	self.add :P92, NS + "P92_brought_into_existence"
	self.add :P92i, NS + "P92i_was_brought_into_existence_by"
	self.add :P93, NS + "P93_took_out_of_existence"
	self.add :P93i, NS + "P93i_was_taken_out_of_existence_by"
	self.add :P94, NS + "P94_has_created"
	self.add :P94i, NS + "P94i_was_created_by"
	self.add :P95, NS + "P95_has_formed"
	self.add :P95i, NS + "P95i_was_formed_by"
	self.add :P96, NS + "P96_by_mother"
	self.add :P96i, NS + "P96i_gave_birth"
	self.add :P97, NS + "P97_from_father"
	self.add :P97i, NS + "P97i_was_father_for"
	self.add :P98, NS + "P98_brought_into_life"
	self.add :P98i, NS + "P98i_was_born"
	self.add :P99, NS + "P99_dissolved"
	self.add :P99i, NS + "P99i_was_dissolved_by"
	self.add :P100, NS + "P100_was_death_of"
	self.add :P100i, NS + "P100i_died_in"
	self.add :P101, NS + "P101_had_as_general_use"
	self.add :P101i, NS + "P101i_was_use_of"
	self.add :P102, NS + "P102_has_title"
	self.add :P102i, NS + "P102i_is_title_of"
	self.add :P103, NS + "P103_was_intended_for"
	self.add :P103i, NS + "P103i_was_intention_of"
	self.add :P104, NS + "P104_is_subject_to"
	self.add :P104i, NS + "P104i_applies_to"
	self.add :P105, NS + "P105_right_held_by"
	self.add :P105i, NS + "P105i_has_right_on"
	self.add :P106, NS + "P106_is_composed_of"
	self.add :P106i, NS + "P106i_forms_part_of"
	self.add :P107, NS + "P107_has_current_or_former_member"
	self.add :P107i, NS + "P107i_is_current_or_former_member_of"
	self.add :P108, NS + "P108_has_produced"
	self.add :P108i, NS + "P108i_was_produced_by"
	self.add :P109, NS + "P109_has_current_or_former_curator"
	self.add :P109i, NS + "P109i_is_current_or_former_curator_of"
	self.add :P110, NS + "P110_augmented"
	self.add :P110i, NS + "P110i_was_augmented_by"
	self.add :P111, NS + "P111_added"
	self.add :P111i, NS + "P111i_was_added_by"
	self.add :P112, NS + "P112_diminished"
	self.add :P112i, NS + "P112i_was_diminished_by"
	self.add :P113, NS + "P113_removed"
	self.add :P113i, NS + "P113i_was_removed_by"
	self.add :P114, NS + "P114_is_equal_in_time_to"
	self.add :P115, NS + "P115_finishes"
	self.add :P115i, NS + "P115i_is_finished_by"
	self.add :P116, NS + "P116_starts"
	self.add :P116i, NS + "P116i_is_started_by"
	self.add :P117, NS + "P117_occurs_during"
	self.add :P117i, NS + "P117i_includes"
	self.add :P118, NS + "P118_overlaps_in_time_with"
	self.add :P118i, NS + "P118i_is_overlapped_in_time_by"
	self.add :P119, NS + "P119_meets_in_time_with"
	self.add :P119i, NS + "P119i_is_met_in_time_by"
	self.add :P120, NS + "P120_occurs_before"
	self.add :P120i, NS + "P120i_occurs_after"
	self.add :P121, NS + "P121_overlaps_with"
	self.add :P122, NS + "P122_borders_with"
	self.add :P123, NS + "P123_resulted_in"
	self.add :P123i, NS + "P123i_resulted_from"
	self.add :P124, NS + "P124_transformed"
	self.add :P124i, NS + "P124i_was_transformed_by"
	self.add :P125, NS + "P125_used_object_of_type"
	self.add :P125i, NS + "P125i_was_type_of_object_used_in"
	self.add :P126, NS + "P126_employed"
	self.add :P126i, NS + "P126i_was_employed_in"
	self.add :P127, NS + "P127_has_broader_term"
	self.add :P127i, NS + "P127i_has_narrower_term"
	self.add :P128, NS + "P128_carries"
	self.add :P128i, NS + "P128i_is_carried_by"
	self.add :P129, NS + "P129_is_about"
	self.add :P129i, NS + "P129i_is_subject_of"
	self.add :P130, NS + "P130_shows_features_of"
	self.add :P130i, NS + "P130i_features_are_also_found_on"
	self.add :P131, NS + "P131_is_identified_by"
	self.add :P131i, NS + "P131i_identifies"
	self.add :P132, NS + "P132_overlaps_with"
	self.add :P133, NS + "P133_is_separated_from"
	self.add :P134, NS + "P134_continued"
	self.add :P134i, NS + "P134i_was_continued_by"
	self.add :P135, NS + "P135_created_type"
	self.add :P135i, NS + "P135i_was_created_by"
	self.add :P136, NS + "P136_was_based_on"
	self.add :P136i, NS + "P136i_supported_type_creation"
	self.add :P137, NS + "P137_exemplifies"
	self.add :P137i, NS + "P137i_is_exemplified_by"
	self.add :P138, NS + "P138_represents"
	self.add :P138i, NS + "P138i_has_representation"
	self.add :P139, NS + "P139_has_alternative_form"
	self.add :P140, NS + "P140_assigned_attribute_to"
	self.add :P140i, NS + "P140i_was_attributed_by"
	self.add :P141, NS + "P141_assigned"
	self.add :P141i, NS + "P141i_was_assigned_by"
	self.add :P142, NS + "P142_used_constituent"
	self.add :P142i, NS + "P142i_was_used_in"
	self.add :P143, NS + "P143_joined"
	self.add :P143i, NS + "P143i_was_joined_by"
	self.add :P144, NS + "P144_joined_with"
	self.add :P144i, NS + "P144i_gained_member_by"
	self.add :P145, NS + "P145_separated"
	self.add :P145i, NS + "P145i_left_by"
	self.add :P146, NS + "P146_separated_from"
	self.add :P146i, NS + "P146i_lost_member_by"
	self.add :P147, NS + "P147_curated"
	self.add :P147i, NS + "P147i_was_curated_by"
	self.add :P148, NS + "P148_has_component"
	self.add :P148i, NS + "P148i_is_component_of"
	end # URI::ECRM


	class CRMEH < Enumeration
	# namespace
	NS = "http://purl.org/crmeh#"
	# entities
	self.add :EHE0001, NS + "EHE0001_EHProject"
  self.add :EHE0002, NS + "EHE0002_ArchaeologicalSite"
  self.add :EHE0003, NS + "EHE0003_AreaOfInvestigation"
  self.add :EHE0004, NS + "EHE0004_SiteSubDivision"
  self.add :EHE0005, NS + "EHE0005_Group"
  self.add :EHE0006, NS + "EHE0006_GroupStuff"
  self.add :EHE0007, NS + "EHE0007_Context"
  self.add :EHE0008, NS + "EHE0008_ContextStuff"
  self.add :EHE0009, NS + "EHE0009_ContextFind"
  self.add :EHE0010, NS + "EHE0010_BulkFind"
  self.add :EHE0011, NS + "EHE0011_GroupEventRecord"
  self.add :EHE0012, NS + "EHE0012_ContextEventRecord"
  self.add :EHE0013, NS + "EHE0013_ContextSheet"
  self.add :EHE0014, NS + "EHE0014_ContextFindProductionEventRecord"
  self.add :EHE0015, NS + "EHE0015_ContextFindUseEventRecord"
  self.add :EHE0016, NS + "EHE0016_RecordDrawing"
  self.add :EHE0017, NS + "EHE0017_RecordPhotograph"
  self.add :EHE0018, NS + "EHE0018_ContextSample"
  self.add :EHE0019, NS + "EHE0019_AreaOfInvestigationDepiction"
  self.add :EHE0020, NS + "EHE0020_BulkFindComponentCount"
  self.add :EHE0021, NS + "EHE0021_EHProjectTimespan"
  self.add :EHE0022, NS + "EHE0022_ContextDepiction"
  self.add :EHE0023, NS + "EHE0023_ContextEventRecordNote"
  self.add :EHE0024, NS + "EHE0024_ContextEventRecordNoteType"
  self.add :EHE0025, NS + "EHE0025_ContextEventTimespan"
  self.add :EHE0026, NS + "EHE0026_ContextEventTimespanAppellation"
  self.add :EHE0027, NS + "EHE0027_ContextFindConditionAssessmentEventTimespan"
  self.add :EHE0028, NS + "EHE0028_ContextFindConditionAssessmentEventType"
  self.add :EHE0029, NS + "EHE0029_ContextFindConditionState"
  self.add :EHE0030, NS + "EHE0030_ContextFindMaterial"
  self.add :EHE0031, NS + "EHE0031_ContextFindMeasurement"
  self.add :EHE0032, NS + "EHE0032_ContextFindMeasurementEventTimespan"
  self.add :EHE0033, NS + "EHE0033_ContextFindMeasurementEventType"
  self.add :EHE0034, NS + "EHE0034_ContextFindMeasurementUnit"
  self.add :EHE0035, NS + "EHE0035_ContextFindMeasurementValue"
  self.add :EHE0036, NS + "EHE0036_ContextFindProductionEventRecordNote"
  self.add :EHE0037, NS + "EHE0037_ContextFindProductionEventRecordNoteType"
  self.add :EHE0038, NS + "EHE0038_ContextFindProductionEventTimespan"
  self.add :EHE0039, NS + "EHE0039_ContextFindProductionEventTimespanAppellation"
  self.add :EHE0040, NS + "EHE0040_ContextFindTreatmentLocation"
  self.add :EHE0041, NS + "EHE0041_ContextFindTreatmentProcedure"
  self.add :EHE0042, NS + "EHE0042_ContextFindTreatmentType"
  self.add :EHE0043, NS + "EHE0043_ContextFindUID"
  self.add :EHE0044, NS + "EHE0044_ContextFindUseEventRecordNote"
  self.add :EHE0045, NS + "EHE0045_ContextFindUseEventRecordNoteType"
  self.add :EHE0046, NS + "EHE0046_ContextNote"
  self.add :EHE0047, NS + "EHE0047_ContextNoteType"
  self.add :EHE0048, NS + "EHE0048_ContextRecord"
  self.add :EHE0049, NS + "EHE0049_ContextSampleMeasurement"
  self.add :EHE0050, NS + "EHE0050_ContextSampleMeasurementType"
  self.add :EHE0051, NS + "EHE0051_ContextSampleMeasurementUnit"
  self.add :EHE0052, NS + "EHE0052_ContextSampleMeasurementValue"
  self.add :EHE0053, NS + "EHE0053_ContextSampleType"
  self.add :EHE0054, NS + "EHE0054_ContextStuffMeasurement"
  self.add :EHE0055, NS + "EHE0055_ContextStuffMeasurementEventTimespan"
  self.add :EHE0056, NS + "EHE0056_ContextStuffMeasurementEventType"
  self.add :EHE0057, NS + "EHE0057_ContextStuffMeasurementUnit"
  self.add :EHE0058, NS + "EHE0058_ContextStuffMeasurementValue"
  self.add :EHE0059, NS + "EHE0059_ContextStuffNote"
  self.add :EHE0060, NS + "EHE0060_ContextStuffNoteType"
  self.add :EHE0061, NS + "EHE0061_ContextUID"
  self.add :EHE0062, NS + "EHE0062_FlotationSample"
  self.add :EHE0063, NS + "EHE0063_FlotationSampleResidue"
  self.add :EHE0064, NS + "EHE0064_FlotationSampleResidueMeasurement"
  self.add :EHE0065, NS + "EHE0065_FlotationSampleResidueMeasurementUnit"
  self.add :EHE0066, NS + "EHE0066_FlotationSampleResidueMeasurementValue"
  self.add :EHE0067, NS + "EHE0067_FlotationSampleResidueType"
  self.add :EHE0068, NS + "EHE0068_GroupEventRecordNote"
  self.add :EHE0069, NS + "EHE0069_GroupEventRecordNoteType"
  self.add :EHE0070, NS + "EHE0070_GroupEventTimespan"
  self.add :EHE0071, NS + "EHE0071_GroupEventTimespanAppellation"
  self.add :EHE0072, NS + "EHE0072_GroupEventType"
  self.add :EHE0073, NS + "EHE0073_GroupingPhasingProcedure"
  self.add :EHE0074, NS + "EHE0074_IdentifiedFeature"
  self.add :EHE0075, NS + "EHE0075_IdentifiedFeatureDepiction"
  self.add :EHE0076, NS + "EHE0076_ProjectDesign"
  self.add :EHE0077, NS + "EHE0077_ProjectTeamMember"
  self.add :EHE0078, NS + "EHE0078_ProjectTeamMemberRole"
  self.add :EHE0079, NS + "EHE0079_RecordDrawingNote"
  self.add :EHE0080, NS + "EHE0080_RecordDrawingNoteType"
  self.add :EHE0081, NS + "EHE0081_RecordDrawingReferenceType"
  self.add :EHE0082, NS + "EHE0082_RecordDrawingSheet"
  self.add :EHE0083, NS + "EHE0083_RecordPhotographNote"
  self.add :EHE0084, NS + "EHE0084_RecordPhotographNoteType"
  self.add :EHE0085, NS + "EHE0085_RecordPhotographReferenceType"
  self.add :EHE0086, NS + "EHE0086_ResponsibleAgent"
  self.add :EHE0087, NS + "EHE0087_SiteSubDivisionAppellation"
  self.add :EHE0088, NS + "EHE0088_SiteSubDivisionDepiction"
  self.add :EHE0089, NS + "EHE0089_StorageLocation"
  self.add :EHE0090, NS + "EHE0090_SurveyDataset"
  self.add :EHE0091, NS + "EHE0091_Timestamp"
  self.add :EHE0092, NS + "EHE0092_GroupUID"
  self.add :EHE0093, NS + "EHE0093_GroupDepiction"
  self.add :EHE0094, NS + "EHE0094_FlotationSampleResidueMeasurementType"
  self.add :EHE0095, NS + "EHE0095_ContextFindProductionEventLocation"
  self.add :EHE0096, NS + "EHE0096_ContextFindGeneralUse"
  self.add :EHE0097, NS + "EHE0097_ContextFindIntendedUse"
  self.add :EHE0098, NS + "EHE0098_ContextFindExcavationEventTimespan"
  self.add :EHE0099, NS + "EHE0099_ContextFindUseEventTimespan"
	self.add :EHE0100, NS + "EHE0100_ContextSamplingEventType"
	self.add :EHE0101, NS + "EHE0101_ArchaeologicalPeriod"
	self.add :EHE0102, NS + "EHE0102_ArchaeologicalPeriodType"
	self.add :EHE0103, NS + "EHE0103_ArchaeologicalPeriodTimespan"
	self.add :EHE0104, NS + "EHE0104_ArchaeologicalPeriodTimestamp"
  self.add :EHE1001, NS + "EHE1001_ContextEvent"
  self.add :EHE1002, NS + "EHE1002_ContextFindProductionEvent"
  self.add :EHE1003, NS + "EHE1003_GroupEvent"
  self.add :EHE1004, NS + "EHE1004_ContextFindDepositionEvent"
  self.add :EHE1005, NS + "EHE1005_ContextFindUseEvent"
  self.add :EHE2001, NS + "EHE2001_ContextExcavationEvent"
  self.add :EHE2002, NS + "EHE2002_ContextFindClassificationEvent"
  self.add :EHE2003, NS + "EHE2003_ContextFindTreatmentEvent"
  self.add :EHE2004, NS + "EHE2004_GroupingPhasingEvent"
  self.add :EHE2005, NS + "EHE2005_ContextFindDatingEvent"
  self.add :EHE2006, NS + "EHE2006_ContextSamplingEvent"
  self.add :EHE2007, NS + "EHE2007_SurveyEvent"
  self.add :EHE2008, NS + "EHE2008_ProcessSurveyDatasetEvent"
  self.add :EHE2009, NS + "EHE2009_TransferObjectEvent"
  self.add :EHE2010, NS + "EHE2010_DepictionEvent"
  self.add :EHE2011, NS + "EHE2011_BulkFindItemRemovalEvent"
  self.add :EHE2012, NS + "EHE2012_ContextFindConditionAssessmentEvent"
  self.add :EHE2013, NS + "EHE2013_ContextFindIdentifierAssignmentEvent"
  self.add :EHE2014, NS + "EHE2014_ContextFindUseAssessmentEvent"
  self.add :EHE2015, NS + "EHE2015_ContextSampleProcessingEvent"
  self.add :EHE2016, NS + "EHE2016_ContextStuffMeasurementEvent"
  self.add :EHE2017, NS + "EHE2017_FlotationSampleProcessingEvent"
  self.add :EHE2018, NS + "EHE2018_FlotationSampleResidueProcessingEvent"
  self.add :EHE2019, NS + "EHE2019_SimpleNameAssignmentEvent"
  self.add :EHE2020, NS + "EHE2020_ContextFindMeasurementEvent"
  self.add :EHE2021, NS + "EHE2021_BulkFindAssessment"		
	# properties
	self.add :EHP1F, NS + "EHP1F_is_trace_of"
  self.add :EHP2F, NS + "EHP2F_is_trace_of_type"
  self.add :EHP3B, NS + "EHP3B_was_occupied_by"
  self.add :EHP3F, NS + "EHP3F_occupied"
  self.add :EHP4B, NS + "EHP4B_is_depicted_by"
  self.add :EHP4F, NS + "EHP4F_depicts"
  self.add :EHP5F, NS + "EHP5F_is_thesaurus_concept"
	end	# URI::CRMEH

	class DC < Enumeration
	# namespace
	NS = "http://purl.org/dc/elements/1.1/"       
  # properties
  self.add :TITLE, NS + "title"
  self.add :CREATOR, NS + "creator"
  self.add :SUBJECT, NS + "subject"
  self.add :DESCRIPTION, NS + "description"
  self.add :PUBLISHER, NS + "publisher"
  self.add :CONTRIBUTOR, NS + "contributor"
  self.add :DATE, NS + "date"
  self.add :TYPE, NS + "type"
  self.add :FORMAT, NS + "format"
  self.add :IDENTIFIER, NS + "identifier"
  self.add :SOURCE, NS + "source"
  self.add :LANGUAGE, NS + "language"
  self.add :RELATION, NS + "relation"
  self.add :COVERAGE, NS + "coverage"
  self.add :RIGHTS, NS + "rights"
	end # URI::DC

	class DCTERMS < Enumeration
	# namespace
	NS = "http://purl.org/dc/terms/"
  # entities
  self.add :SUBJECTSCHEME, NS + "SubjectScheme"
  self.add :DATESCHEME, NS + "DateScheme"
  self.add :FORMATSCHEME, NS + "FormatScheme"
  self.add :LANGUAGESCHEME, NS + "LanguageScheme"
  self.add :SPATIALSCHEME, NS + "SpatialScheme"
  self.add :TEMPORALSCHEME, NS + "TemporalScheme"
  self.add :TYPESCHEME, NS + "TypeScheme"
  self.add :IDENTIFIERSCHEME, NS + "IdentifierScheme"
  self.add :RELATIONSCHEME, NS + "RelationScheme"
  self.add :SOURCESCHEME, NS + "SourceScheme"        
  # properties
  self.add :AUDIENCE, NS + "audience"
  self.add :ALTERNATIVE, NS + "alternative"
  self.add :TABLEOFCONTENTS, NS + "tableOfContents"
  self.add :ABSTRACT, NS + "abstract"
  self.add :CREATED, NS + "created"
  self.add :VALID, NS + "valid"
  self.add :AVAILABLE, NS + "available"
  self.add :ISSUED, NS + "issued"
  self.add :MODIFIED, NS + "modified"
  self.add :EXTENT, NS + "extent"
  self.add :MEDIUM, NS + "medium"
  self.add :ISVERSIONOF, NS + "isVersionOf"
  self.add :HASVERSION, NS + "hasVersion"
  self.add :ISREPLACEDBY, NS + "isReplacedBy"
  self.add :REPLACES, NS + "replaces"
  self.add :ISREQUIREDBY, NS + "isRequiredBy"
  self.add :REQUIRES, NS + "requires"
  self.add :ISPARTOF, NS + "isPartOf"
  self.add :HASPART, NS + "hasPart"
  self.add :ISREFERENCEDBY, NS + "isReferencedBy"
  self.add :REFERENCES, NS + "references"
  self.add :ISFORMATOF, NS + "isFormatOf"
  self.add :HASFORMAT, NS + "hasFormat"
  self.add :CONFORMSTO, NS + "conformsTo"
  self.add :SPATIAL, NS + "spatial"
  self.add :TEMPORAL, NS + "temporal"
  self.add :MEDIATOR, NS + "mediator"
  self.add :DATEACCEPTED, NS + "dateAccepted"
  self.add :DATECOPYRIGHTED, NS + "dateCopyrighted"
  self.add :DATESUBMITTED, NS + "dateSubmitted"
  self.add :EDUCATIONLEVEL, NS + "educationLevel"
  self.add :ACCESSRIGHTS, NS + "accessRights"
  self.add :BIBLIOGRAPHICCITATION, NS + "bibliographicCitation"
  self.add :LICENSE, NS + "license"
  self.add :RIGHTSHOLDER, NS + "rightsHolder"
  self.add :PROVENANCE, NS + "provenance"
  self.add :INSTRUCTIONALMETHOD, NS + "instructionalMethod"
  self.add :ACCRUALMETHOD, NS + "accrualMethod"
  self.add :ACCRUALPERIODICITY, NS + "accrualPeriodicity"
  self.add :ACCRUALPOLICY, NS + "accrualPolicy"
  
  self.add :TITLE, NS + "title"
  self.add :CREATOR, NS + "creator"
  self.add :SUBJECT, NS + "subject"
  self.add :DESCRIPTION, NS + "description"
  self.add :PUBLISHER, NS + "publisher"
  self.add :CONTRIBUTOR, NS + "contributor"
  self.add :DATE, NS + "date"
  self.add :TYPE, NS + "type"
  self.add :FORMAT, NS + "format"
  self.add :IDENTIFIER, NS + "identifier"
  self.add :SOURCE, NS + "source"
  self.add :LANGUAGE, NS + "language"
  self.add :RELATION, NS + "relation"
  self.add :COVERAGE, NS + "coverage"
  self.add :RIGHTS, NS + "rights"
	end # URI::DCTERMS

	class OWL < Enumeration
	# namespace
	NS = "http://www.w3.org/2002/07/owl#"
  # entities
  self.add :ALLDIFFERENT, NS + "AllDifferent"
  self.add :ANNOTATIONPROPERTY, NS + "AnnotationProperty"
  self.add :CLASS, NS + "Class"
  self.add :DATARANGE, NS + "DataRange"
  self.add :DATATYPEPROPERTY, NS + "DatatypeProperty"
  self.add :DEPRECATEDCLASS, NS + "DeprecatedClass"
  self.add :DEPRECATEDPROPERTY, NS + "DeprecatedProperty"
  self.add :FUNCTIONALPROPERTY, NS + "FunctionalProperty"
  self.add :INVERSEFUNCTIONALPROPERTY, NS + "InverseFunctionalProperty"
  self.add :NOTHING, NS + "Nothing"
  self.add :OBJECTPROPERTY, NS + "ObjectProperty"
  self.add :ONTOLOGY, NS + "Ontology"
  self.add :ONTOLOGYPROPERTY, NS + "OntologyProperty"
  self.add :RESTRICTION, NS + "Restriction"
  self.add :SYMMETRICPROPERTY, NS + "SymmetricProperty"
  self.add :THING, NS + "Thing"
  self.add :TRANSITIVEPROPERTY, NS + "TransitiveProperty"
  # properties
  self.add :ALLVALUESFROM, NS + "allValuesFrom"
  self.add :BACKWARDCOMPATIBLEWITH, NS + "backwardCompatibleWith"
  self.add :CARDINALITY, NS + "cardinality"
  self.add :COMPLEMENTOF, NS + "complementOf"
  self.add :DIFFERENTFROM, NS + "differentFrom"
  self.add :DISJOINTWITH, NS + "disjointWith"
  self.add :DISTINCTMEMBERS, NS + "distinctMembers"
  self.add :EQUIVALENTCLASS, NS + "equivalentClass"
  self.add :EQUIVALENTPROPERTY, NS + "equivalentProperty"
  self.add :HASVALUE, NS + "hasValue"
  self.add :IMPORTS, NS + "imports"
  self.add :INCOMPATIBLEWITH, NS + "incompatibleWith"
  self.add :INTERSECTIONOF, NS + "intersectionOf"
  self.add :INVERSEOF, NS + "inverseOf"
  self.add :MAXCARDINALITY, NS + "maxCardinality"
  self.add :MINCARDINALITY, NS + "minCardinality"
  self.add :ONEOF, NS + "oneOf"
  self.add :ONPROPERTY, NS + "onProperty"
  self.add :PRIORVERSION, NS + "priorVersion"
  self.add :SAMEAS, NS + "sameAs"
  self.add :SOMEVALUESFROM, NS + "someValuesFrom"
  self.add :UNIONOF, NS + "unionOf"
  self.add :VERSIONINFO, NS + "versionInfo"
	end # URI::OWL	
end # URI

# test code - usage examples
if __FILE__ == $0 
	puts("URI::CRM42::E1=", URI::CRM42::E1)
	puts("URI::CRM42::P2F=", URI::CRM42::P2F)

	puts("URI::CRMEH::EHE0001=", URI::CRMEH::EHE0001)
	puts("URI::CRMEH::EHP1F=", URI::CRMEH::EHP1F)

	puts("URI::DC::SUBJECT=", URI::DC::SUBJECT)
	puts("URI::DC::DESCRIPTION=", URI::DC::DESCRIPTION)

	puts("URI::DCTERMS::SUBJECT=", URI::DCTERMS::SUBJECT)
	puts("URI::DCTERMS::DESCRIPTION=", URI::DCTERMS::DESCRIPTION)

	puts("URI::ECRM::E1=", URI::ECRM::E1)
	puts("URI::ECRM::P1=", URI::ECRM::P1)

	puts("URI::OWL::CLASS=", URI::OWL::CLASS)
	puts("URI::OWL::CARDINALITY=", URI::OWL::CARDINALITY)

	puts("URI::RDF::PROPERTY=", URI::RDF::PROPERTY)
	puts("URI::RDF::SUBJECT=", URI::RDF::SUBJECT)

	puts("URI::RDFS::RESOURCE=", URI::RDFS::RESOURCE)
	puts("URI::RDFS::DOMAIN=", URI::RDFS::DOMAIN)

	puts("URI::SKOS::PREFLABEL=", URI::SKOS::PREFLABEL)
	puts("URI::SKOS::ALTLABEL=", URI::SKOS::ALTLABEL)

	puts("URI::SKOSXL::PREFLABEL=", URI::SKOSXL::PREFLABEL)
	puts("URI::SKOSXL::ALTLABEL=", URI::SKOSXL::ALTLABEL)

	puts("Testing enumeration:\n")
	URI::RDF.each do |key,value|
		puts "#{key}\t#{value}" 
	end	
end
